const allQuestionsData = [
  { "id": 1, "type": "tf", "q": "Digital art is based on data rather than physical materials", "a": "True" },
  { "id": 2, "type": "tf", "q": "Digital art is only about decoration.", "a": "False" },
  { "id": 3, "type": "tf", "q": "Software can think and create ideas independently.", "a": "False" },
  { "id": 4, "type": "tf", "q": "Intent helps define the purpose of a design.", "a": "True" },
  { "id": 5, "type": "tf", "q": "Random decisions improve communication.", "a": "false" },
  { "id": 6, "type": "tf", "q": "A structured workflow improves design quality", "a": "True" },
  { "id": 7, "type": "tf", "q": "Skipping planning leads to better results", "a": "False" },
  { "id": 8, "type": "tf", "q": "Version 1 is the final design", "a": "False" },
  { "id": 9, "type": "tf", "q": "A workflow helps reduce confusion", "a": "True" },
  { "id": 10, "type": "tf", "q": "Professional designers follow a clear process", "a": "True" },
  { "id": 11, "type": "tf", "q": "Feedback is only personal opinion", "a": "False" },
  { "id": 12, "type": "tf", "q": "Review comes before revision", "a": "True" },
  { "id": 13, "type": "tf", "q": "Random design leads to strong communication", "a": "False" },
  { "id": 14, "type": "tf", "q": "Organization is part of professional work", "a": "True" },
  { "id": 15, "type": "tf", "q": "The workflow stages must always be followed in order without returning back", "a": "False" },
  { "id": 16, "type": "tf", "q": "A design brief is optional", "a": "False" },
  { "id": 17, "type": "tf", "q": "Constraints help guide design decisions", "a": "True" },
  { "id": 18, "type": "tf", "q": "Visual hierarchy controls what the viewer sees first", "a": "True" },
  { "id": 19, "type": "tf", "q": "If all elements are equal, the design has strong hierarchy", "a": "False" },
  { "id": 20, "type": "tf", "q": "Balance affects how stable a design feels", "a": "True" },
  { "id": 21, "type": "tf", "q": "Visual weight depends only on size", "a": "False" },
  { "id": 22, "type": "tf", "q": "Low contrast improves readability", "a": "False" },
  { "id": 23, "type": "tf", "q": "Alignment has no effect on design clarity", "a": "False" },
  { "id": 24, "type": "tf", "q": "Spacing helps reduce visual noise", "a": "True" },
  { "id": 25, "type": "tf", "q": "RGB is a color model based on Red, Green, and Blue.", "a": "True" },
  { "id": 26, "type": "tf", "q": "HEX code represents color using 6 characters.", "a": "True" },
  { "id": 27, "type": "tf", "q": "RGB values range from 0 to 100.", "a": "False" },
  { "id": 28, "type": "tf", "q": "HEX colors are only used in printing.", "a": "False" },
  { "id": 29, "type": "tf", "q": "color in digital design is controlled by numerical values", "a": "True" },
  { "id": 30, "type": "tf", "q": "Designers choose colors randomly without data", "a": "False" },
  { "id": 31, "type": "tf", "q": "Typography only decorates text", "a": "False" },
  { "id": 32, "type": "tf", "q": "Typography helps organize content", "a": "True" },
  { "id": 33, "type": "tf", "q": "All text should have the same size", "a": "False" },
  { "id": 34, "type": "mcq", "q": "Digital art depends on:", "opts": ["Physical materials", "Data", "Ink"], "a": "data" },
  { "id": 35, "type": "mcq", "q": "The main goal of design is:", "opts": ["Decoration", "Communication", "Randomness", "Effects"], "a": "communication" },
  { "id": 36, "type": "mcq", "q": "The first stage of workflow is", "opts": ["Intent", "Plan", "Review", "Export"], "a": "Intent" },
  { "id": 37, "type": "mcq", "q": "The purpose of a design brief is to define", "opts": ["Effects", "Audience and message", "message", "Colors only"], "a": "Audience and message" },
  { "id": 38, "type": "mcq", "q": "Version 1 is", "opts": ["First draft", "second draft", "Exported file", "Finished work"], "a": "First draft" },
  { "id": 39, "type": "mcq", "q": "Feedback should be treated as", "opts": ["Opinion", "Decoration", "Technical", "Technical input"], "a": "Technical input" },
  { "id": 40, "type": "mcq", "q": "A structured workflow", "opts": ["reduces Creativity", "Confusion", "Quality"], "a": "Confusion" },
  { "id": 41, "type": "mcq", "q": "RGB stands for", "opts": ["Red Green Black", "Red Green Blue", "Random Gradient Base", "Real Graphic Balance"], "a": "Red Green Blue" },
  { "id": 42, "type": "mcq", "q": "Which of the following is a HEX color?", "opts": ["(255, 0, 0)", "#FF0000", "RGB(0,0,0)", "Blue"], "a": "#FF0000" },
  { "id": 43, "type": "mcq", "q": "Color in digital systems is", "opts": ["Emotional only", "Random", "Data based", "Printed only"], "a": "Data based" },
  { "id": 44, "type": "mcq", "q": "Typography is used to", "opts": ["Add random decoration", "Structure and organize content", "Only change colors", "Remove text"], "a": "Structure and organize content" },
  { "id": 45, "type": "essay", "q": "Complete: Digital art is a system of input, __________, and output.", "a": "transformation" },
  { "id": 46, "type": "essay", "q": "Complete: Creativity exists in your __________, not in the tool.", "a": "decisions" },
  { "id": 47, "type": "essay", "q": "Complete: A good design must communicate a clear __________.", "a": "message" },
  { "id": 48, "type": "essay", "q": "Complete: The process of improving design is called __________.", "a": "iteration" },
  { "id": 49, "type": "essay", "q": "Complete: Before designing, you must define your __________.", "a": "intent" },
  { "id": 50, "type": "essay", "q": "Complete: A workflow is a clear order of __________", "a": "steps" },
  { "id": 51, "type": "essay", "q": "Complete: The first stage of workflow is __________", "a": "intent" },
  { "id": 52, "type": "essay", "q": "Complete: Version 1 is the __________ version of the design", "a": "first" },
  { "id": 53, "type": "essay", "q": "Complete: Feedback is considered _________ input", "a": "technical" },
  { "id": 54, "type": "essay", "q": "Complete: Revision focuses on __________ improvement", "a": "controlled" },
  { "id": 55, "type": "essay", "q": "Complete: A design brief defines the __________ and audience", "a": "message" },
  { "id": 56, "type": "essay", "q": "Complete: Constraints help reduce __________ decisions", "a": "random" },
  { "id": 57, "type": "essay", "q": "Complete: The final stage is called __________", "a": "final output" },
  { "id": 58, "type": "essay", "q": "Complete: Review helps identify __________", "a": "weaknesses" },
  { "id": 59, "type": "essay", "q": "Complete: Professional designers avoid __________ changes", "a": "random" },
  { "id": 60, "type": "essay", "q": "Complete: Hierarchy controls viewer __________", "a": "attention" },
  { "id": 61, "type": "essay", "q": "Complete: Balance creates visual __________", "a": "stability" },
  { "id": 62, "type": "essay", "q": "Complete: Contrast improves __________", "a": "readability" },
  { "id": 63, "type": "essay", "q": "Complete: Spacing reduces visual __________", "a": "noise" },
  { "id": 64, "type": "essay", "q": "Complete: Alignment creates __________", "a": "clarity" },
  { "id": 65, "type": "essay", "q": "Complete: Visual weight depends on color and __________", "a": "size" },
  { "id": 66, "type": "essay", "q": "Complete: Good composition improves __________", "a": "attention" },
  { "id": 67, "type": "essay", "q": "Complete: RGB values range from ___ to ___", "a": "0 to 255" },
  { "id": 68, "type": "essay", "q": "Complete: HEX color starts with ___", "a": "#" },
  { "id": 69, "type": "essay", "q": "Complete: Color is made of _________", "a": "numbers/data" },
  { "id": 70, "type": "essay", "q": "Complete: Designers control color using __________ values", "a": "numeric" },
  { "id": 71, "type": "essay", "q": "Compare: digital art & traditional art", "a": "Digital art allows undo and editing while traditional art is hard to correct" },
  { "id": 72, "type": "essay", "q": "Compare: random design & intentional design", "a": "Random design has weak communication while intentional design has strong communication" },
  { "id": 73, "type": "essay", "q": "Compare: tools & decisions", "a": "Tools execute actions while decisions create meaning" },
  { "id": 74, "type": "essay", "q": "Compare: clear design & cluttered design", "a": "Clear design is easy to read while cluttered design is difficult to read" },
  { "id": 75, "type": "essay", "q": "Compare: decoration-based design & communication-based design", "a": "Decoration-based design focuses on appearance while communication-based design focuses on message" },
  { "id": 76, "type": "essay", "q": "Compare: transformation & output", "a": "Transformation is the process while output is the final result" },
  { "id": 77, "type": "essay", "q": "Compare: structured design & unstructured design", "a": "Structured design is organized while unstructured design is random" },
  { "id": 78, "type": "essay", "q": "Compare: structured workflow & random workflow", "a": "Structured workflow follows clear steps while random workflow has no order" },
  { "id": 79, "type": "essay", "q": "Compare: Version 1 & final output", "a": "Version 1 is the first draft while final output is the refined result" },
  { "id": 80, "type": "essay", "q": "Compare: review & revise", "a": "Review identifies problems while revise improves them" },
  { "id": 81, "type": "essay", "q": "Compare: brief-based design & no-brief design", "a": "Brief-based design is clear and focused while no-brief design is random" },
  { "id": 82, "type": "essay", "q": "Compare: feedback & opinion", "a": "Feedback is logical and structured while opinion is personal" },
  { "id": 83, "type": "essay", "q": "Compare: planning & random start", "a": "Planning organizes ideas while random start causes confusion" },
  { "id": 84, "type": "essay", "q": "Compare: hierarchy & no hierarchy", "a": "Hierarchy guides the viewer’s attention; no hierarchy creates confusion" },
  { "id": 85, "type": "essay", "q": "Compare: symmetrical balance & asymmetrical balance", "a": "Symmetrical balance feels stable; asymmetrical balance feels dynamic" },
  { "id": 86, "type": "essay", "q": "Compare: high contrast & low contrast", "a": "High contrast improves readability; low contrast reduces readability" },
  { "id": 87, "type": "essay", "q": "Compare: aligned design & misaligned design", "a": "Aligned design creates clarity; misaligned design creates disorder" },
  { "id": 88, "type": "essay", "q": "Compare: spaced layout & crowded layout", "a": "Spaced layout reduces visual noise; crowded layout feels cluttered" },
  { "id": 89, "type": "essay", "q": "Mention: the components of a good design", "a": "Visual choices, Technical tools, Human understanding" },
  { "id": 90, "type": "essay", "q": "Mention: the parts of the digital art system", "a": "Input, Transformation, Output" },
  { "id": 91, "type": "essay", "q": "Mention: three actions possible in digital art", "a": "Move, Resize, Delete" },
  { "id": 92, "type": "essay", "q": "Mention: the six stages of workflow", "a": "Intent, Plan, Create, Review, Revise, Final Output" },
  { "id": 93, "type": "essay", "q": "Mention: the five parts of a design brief", "a": "Project goal, Target audience, Main message, Platform, Constraints" },
  { "id": 94, "type": "essay", "q": "Mention: three benefits of structured workflow", "a": "Reduce confusion, Save time, Improve quality" },
  { "id": 95, "type": "essay", "q": "Mention: three problems caused by skipping planning", "a": "Confusion, Weak structure, Poor communication" },
  { "id": 96, "type": "essay", "q": "Mention: three elements checked in feedback", "a": "Clarity, Hierarchy, Alignment" },
  { "id": 97, "type": "essay", "q": "Mention: Four tools that control hierarchy", "a": "Size, Color, Position/Layout, Typography" },
  { "id": 98, "type": "essay", "q": "Mention: Four factors affecting visual weight", "a": "Size, Color, Shape, Texture or Density" },
  { "id": 99, "type": "essay", "q": "Mention: four types of contrast", "a": "Color contrast, Size contrast, Shape contrast, Texture contrast" },
  { "id": 100, "type": "essay", "q": "Mention: four problems caused by low contrast", "a": "Poor readability, Eye strain, Important elements overlooked, Confusion or lack of focus" },
  { "id": 101, "type": "essay", "q": "Mention: four benefits of spacing", "a": "Reduces visual noise, Improves readability, Organizes elements clearly, Guides viewer attention" },
  { "id": 102, "type": "essay", "q": "Define: Intent", "a": "Intent is the purpose, audience, and message of a design" },
  { "id": 103, "type": "essay", "q": "Define: Iteration", "a": "Iteration is the process of improving a design through multiple versions" },
  { "id": 104, "type": "essay", "q": "Define: Transformation", "a": "Transformation is the process of converting an idea into a visual form" },
  { "id": 105, "type": "essay", "q": "Define: Input", "a": "Input is the original idea of the design" },
  { "id": 106, "type": "essay", "q": "Define: Output", "a": "Output is the final visual result" },
  { "id": 107, "type": "essay", "q": "Define: Visual Communication", "a": "Visual communication is delivering a message through visuals" },
  { "id": 108, "type": "essay", "q": "Define: Design System", "a": "A design system is a structured process of input, transformation, and output" },
  { "id": 109, "type": "essay", "q": "Define: Reversibility", "a": "Reversibility is the ability to undo and modify actions" },
  { "id": 110, "type": "essay", "q": "Define: Random Design", "a": "Random design is creating visuals without intent" },
  { "id": 111, "type": "essay", "q": "Define: Intentional Design", "a": "Intentional design is creating visuals based on purpose" },
  { "id": 112, "type": "essay", "q": "Define: Clarity", "a": "Clarity is how easily the message is understood" },
  { "id": 113, "type": "essay", "q": "Define: Visual Noise", "a": "Visual noise is unnecessary elements that reduce clarity" },
  { "id": 114, "type": "essay", "q": "Define: Structured Design", "a": "Structured design is organized and clear" },
  { "id": 115, "type": "essay", "q": "Define: Unstructured Design", "a": "unstructured design is a design created without planning, clear goals, or a defined process." },
  { "id": 116, "type": "essay", "q": "Define: structured workflow", "a": "A structured workflow is a sequence of steps used to complete a design professionally" },
  { "id": 117, "type": "essay", "q": "Define: design brief", "a": "A design brief is a short document that defines the goal, audience, and message" },
  { "id": 118, "type": "essay", "q": "Define: feedback", "a": "Feedback is structured evaluation used to improve design" },
  { "id": 119, "type": "essay", "q": "Define: revision", "a": "Revision is controlled improvement of specific elements" },
  { "id": 120, "type": "essay", "q": "Define: refinement", "a": "Refinement is improving small details for precision" },
  { "id": 121, "type": "essay", "q": "Define: visual hierarchy", "a": "Visual Hierarchy – The arrangement of elements in a design that guides the viewer’s attention and shows what is most important first." },
  { "id": 122, "type": "essay", "q": "Define: balance", "a": "Balance – The distribution of visual elements in a design to create a sense of stability and harmony." },
  { "id": 123, "type": "essay", "q": "Define: visual weight", "a": "Visual Weight – How much an element attracts the viewer’s attention based on its size, color, shape, and texture." },
  { "id": 124, "type": "essay", "q": "Define: contrast", "a": "Contrast – The difference between elements, such as color, size, or shape," },
  { "id": 125, "type": "essay", "q": "Define: spacing", "a": "Spacing – The empty space between elements in a design that reduces clutter and improves clarity." },
  { "id": 126, "type": "essay", "q": "Explain: why digital art is considered a system", "a": "Because it consists of input, transformation, and output working together" },
  { "id": 127, "type": "essay", "q": "Explain: why decisions are more important than tools", "a": "Because tools only execute while decisions create meaning" },
  { "id": 128, "type": "essay", "q": "Explain: why intent must be defined before designing", "a": "Because it guides all design choices" },
  { "id": 129, "type": "essay", "q": "Explain: how iteration improves design quality", "a": "Because it allows continuous improvement" },
  { "id": 130, "type": "essay", "q": "Explain: why digital art allows experimentation", "a": "Because actions can be undone easily" },
  { "id": 131, "type": "essay", "q": "Explain: the role of transformation in design", "a": "Because it converts the idea into a visual form" },
  { "id": 132, "type": "essay", "q": "Explain: why a design may fail even if it looks good", "a": "Because it may not communicate the message" },
  { "id": 133, "type": "essay", "q": "Explain: how clarity affects communication", "a": "Because clear design improves understanding" },
  { "id": 134, "type": "essay", "q": "Explain: why designers should think before using tools", "a": "Because planning leads to better results" },
  { "id": 135, "type": "essay", "q": "Explain: why structured workflow improves design quality", "a": "Because it organizes steps and improves clarity and quality" },
  { "id": 136, "type": "essay", "q": "Explain: why Version 1 is not final", "a": "Because it is only the first attempt and may contain mistakes" },
  { "id": 137, "type": "essay", "q": "Explain: why feedback is important in design", "a": "Because it identifies weaknesses and improves clarity" },
  { "id": 138, "type": "essay", "q": "Explain: how constraints improve creativity", "a": "Because constraints guide decisions and reduce randomness" },
  { "id": 139, "type": "essay", "q": "Explain: why planning is important before designing", "a": "Because it defines structure and prevents confusion" },
  { "id": 140, "type": "essay", "q": "Explain: how organization helps designers", "a": "Because it keeps files organized and easy to manage" },
  { "id": 141, "type": "essay", "q": "Explain: why workflow is iterative not linear", "a": "Because designers may return to improve earlier stages" },
  { "id": 142, "type": "essay", "q": "Explain: how revision improves communication", "a": "Because it fixes weaknesses and improves clarity" },
  { "id": 143, "type": "essay", "q": "Explain: Why is typography considered structure, not decoration؟", "a": "Because it organizes content and guides the reader" },
  { "id": 144, "type": "essay", "q": "List: the three main questions designers must answer before designing", "a": "What is the message, Who is the audience, How to make the message clear" },
  { "id": 145, "type": "essay", "q": "List: the stages of the digital art system", "a": "Input, Transformation, Output, Iteration, Communication" },
  { "id": 146, "type": "essay", "q": "List: four characteristics of digital art", "a": "Editable, Flexible, Data-based, Reversible" },
  { "id": 147, "type": "essay", "q": "List: four design elements that affect communication", "a": "Color, Typography, Layout, Contrast" },
  { "id": 148, "type": "essay", "q": "List: four advantages of digital art", "a": "Easy editing, Undo feature, Fast changes, Multiple versions" },
  { "id": 149, "type": "essay", "q": "List: four problems caused by random design", "a": "Confusion, Weak message, Visual noise, Poor structure" },
  { "id": 150, "type": "essay", "q": "List: four features of a good design", "a": "Clarity, Organization, Strong message, Hierarchy" },
  { "id": 151, "type": "essay", "q": "List: four roles of design decisions", "a": "Control layout, Improve clarity, Guide attention, Support message" },
  { "id": 152, "type": "essay", "q": "List: four reasons why intent is important", "a": "Defines purpose, Guides decisions, Improves clarity, Prevents randomness" },
  { "id": 153, "type": "tf", "q": "UX focuses on user experience", "a": "T" },
  { "id": 154, "type": "tf", "q": "UI is only about code.", "a": "F" },
  { "id": 155, "type": "tf", "q": "Animation adds movement to visuals", "a": "T" },
  { "id": 156, "type": "tf", "q": "Workflow helps organize design steps", "a": "T" },
  { "id": 157, "type": "tf", "q": "Designers can ignore users", "a": "F" },
  { "id": 158, "type": "tf", "q": "Feedback improves design quality", "a": "T" },
  { "id": 159, "type": "tf", "q": "UI and UX are identical", "a": "F" },
  { "id": 160, "type": "tf", "q": "Testing is part of workflow", "a": "T" },
  { "id": 161, "type": "tf", "q": "Good UX makes products easy to use", "a": "T" },
  { "id": 162, "type": "tf", "q": "Animation is only used in movies", "a": "F" },
  { "id": 163, "type": "mcq", "q": "UX means:", "opts": ["User Experience", "User Export", "User Example", "User Effect"], "a": "A" },
  { "id": 164, "type": "mcq", "q": "UI focuses on:", "opts": ["Code", "Visual interface", "Sound", "Testing"], "a": "B" },
  { "id": 165, "type": "mcq", "q": "Animation is:", "opts": ["Static", "Moving visuals", "Text", "Code"], "a": "B" },
  { "id": 166, "type": "mcq", "q": "Workflow helps to:", "opts": ["Confuse", "Organize", "Delete", "Ignore"], "a": "B" },
  { "id": 167, "type": "mcq", "q": "Good UX should be:", "opts": ["Complex", "Easy to use", "Random", "Difficult"], "a": "B" },
  { "id": 168, "type": "essay", "q": "Complete: UI stands for user __________", "a": "interface" },
  { "id": 169, "type": "essay", "q": "Complete: UX focuses on user __________", "a": "experience" },
  { "id": 170, "type": "essay", "q": "Complete: Workflow is a sequence of __________", "a": "steps" },
  { "id": 171, "type": "essay", "q": "Complete: Animation adds __________ to design", "a": "movement" },
  { "id": 172, "type": "essay", "q": "Complete: Feedback improves __________", "a": "quality" },
  { "id": 173, "type": "essay", "q": "Explain what UX means", "a": "UX means how users feel when using a product." },
  { "id": 174, "type": "essay", "q": "Explain what UI means", "a": "UI means the visual design and layout users interact with visually" },
  { "id": 175, "type": "essay", "q": "Explain the difference between UI and UX", "a": "UI is the look, UX is the experience" },
  { "id": 176, "type": "essay", "q": "Explain why UX is important in design", "a": "UX is important because it makes products easy and enjoyable." },
  { "id": 177, "type": "essay", "q": "Explain the role of UI in application", "a": "UI helps users interact with the system visually" },
  { "id": 178, "type": "essay", "q": "Explain how workflow improves design quality", "a": "Workflow organizes steps and improves efficiency" },
  { "id": 179, "type": "essay", "q": "Explain why planning is important before designing", "a": "Planning avoids mistakes and saves time." },
  { "id": 180, "type": "essay", "q": "Explain the importance of feedback", "a": "Feedback helps improve and fix problems" },
  { "id": 181, "type": "essay", "q": "Explain the role of testing in UX", "a": "Testing ensures the design works correctly and meets user needs" },
  { "id": 182, "type": "essay", "q": "Explain how animation improves user experience", "a": "Animation makes design more engaging and clearer" },
  { "id": 183, "type": "essay", "q": "Explain why designers must understand users", "a": "Designers must understand users to meet their needs." },
  { "id": 184, "type": "essay", "q": "Explain how UI affects UX", "a": "UI affects UX by making interaction easy or difficult" },
  { "id": 185, "type": "essay", "q": "Explain why workflow is not random", "a": "Workflow is structured to ensure good results." },
  { "id": 186, "type": "essay", "q": "Explain how iteration improves design", "a": "Iteration improves design through repeated enhancement." },
  { "id": 187, "type": "essay", "q": "Explain why revision is important", "a": "Revision fixes errors and improves quality." },
  { "id": 188, "type": "essay", "q": "Explain how animation can guide attention", "a": "Animation guides user attention to important elements." },
  { "id": 189, "type": "essay", "q": "Explain why simple design improves UX", "a": "Simple design makes usage easier." },
  { "id": 190, "type": "essay", "q": "Explain how interaction improves user experience", "a": "Interaction makes the experience engaging." },
  { "id": 191, "type": "essay", "q": "Explain why consistency is important in UI", "a": "Consistency makes design predictable and easy." },
  { "id": 192, "type": "essay", "q": "Explain how poor UX affects users", "a": "Poor UX causes confusion and frustration." },
  { "id": 193, "type": "essay", "q": "Compare UI vs UX", "a": "UI: Visual design, colors, buttons, layout, appearance. UX: User experience, usability, flow, satisfaction, ease of use" },
  { "id": 194, "type": "essay", "q": "Compare Good UX vs bad UX", "a": "Good UX: Easy, fast, clear navigation, user-friendly, efficient. Bad UX: Confusing, slow, hard to navigate, frustrating, inefficient" },
  { "id": 195, "type": "essay", "q": "Compare Animation vs static design", "a": "Animation: Movement, interactive, engaging, guides attention, dynamic. Static: No movement, simple, less engaging, fixed content" },
  { "id": 196, "type": "essay", "q": "Compare Structured workflow vs random workflow", "a": "Structured: Organized steps, clear process, efficient, predictable results. Random: No order, confusing process, inefficient, inconsistent results" },
  { "id": 197, "type": "essay", "q": "Compare Planning vs no planning", "a": "Planning: Clear goals, saves time, reduces errors, better results. No planning: Wasted time, more errors, unclear direction, poor results" },
  { "id": 198, "type": "essay", "q": "Compare Feedback vs ignoring feedback", "a": "Feedback: Improves quality, fixes mistake, enhances usability, user-centered. Ignoring: Repeated errors, poor quality, user dissatisfaction" },
  { "id": 199, "type": "essay", "q": "Compare Testing vs, no testing", "a": "Testing: Finds issues, improves performance, ensures quality, reliable. No testing: Bugs remain, poor performance, unreliable system" },
  { "id": 200, "type": "essay", "q": "Compare Interactive design vs non-interactive design", "a": "Interactive: User engagement, clickable elements, dynamic, responsive. Non-interactive: Passive, no user control, less engaging, static" },
  { "id": 201, "type": "essay", "q": "Compare Simple UI vs complex UI", "a": "Simple: Clean, easy, fast to use, clear navigation, user-friendly. Complex: Cluttered, confusing, slow, difficult navigation" },
  { "id": 202, "type": "essay", "q": "Compare Consistent design vs inconsistent design", "a": "Consistent: Same style, predictable, easy to learn, professional. Inconsistent: Different styles, confusing, hard to use, unprofessional" },
  { "id": 203, "type": "essay", "q": "Compare RGB vs HEX", "a": "RGB uses numeric values for each color channel, while HEX is a coded representation of the same values used in digital design." },
  { "id": 204, "type": "essay", "q": "Mention the stages of creative workflow", "a": "Workflow stages: Planning – Design – Testing" },
  { "id": 205, "type": "essay", "q": "Mention three goals of UX design", "a": "UX goals: Easy – Useful – Enjoyable" },
  { "id": 206, "type": "essay", "q": "Mention three UI elements", "a": "UI elements: Buttons – Icons – Colors" },
  { "id": 207, "type": "essay", "q": "Mention three benefits of animation", "a": "Animation benefits: Engagement – Clarity – Guidance" },
  { "id": 208, "type": "essay", "q": "Mention three uses of animation", "a": "Animation uses: Apps – Websites – Games" },
  { "id": 209, "type": "essay", "q": "Mention three benefits of workflow", "a": "Workflow benefits: Organization – Efficiency – Quality" },
  { "id": 210, "type": "essay", "q": "Mention three problems of bad UX", "a": "Bad UX problems: Confusion – Errors – Frustration" },
  { "id": 211, "type": "essay", "q": "Mention three features of good UX", "a": "Good UX features: Simple – Clear – Fast" },
  { "id": 212, "type": "essay", "q": "Mention three features of good UI", "a": "Good UI features: Clean – Consistent – Attractive" },
  { "id": 213, "type": "essay", "q": "Mention three steps of testing", "a": "Testing steps: Check – Fix – Retest" },
  { "id": 214, "type": "essay", "q": "Mention three benefits of feedback", "a": "Feedback benefits: Improve – Correct – Develop" },
  { "id": 215, "type": "essay", "q": "Mention three types of user interaction", "a": "Interaction types: Click – Scroll – Drag" },
  { "id": 216, "type": "essay", "q": "Mention three design decisions affecting UX", "a": "UX decisions: Layout – Color – Navigation" },
  { "id": 217, "type": "essay", "q": "Mention three advantages of simple design", "a": "Simple design advantages: Easy – Fast – Clear" },
  { "id": 218, "type": "essay", "q": "Mention three problems of complex design", "a": "Complex design problems: Confusing – Slow – Difficult" },
  { "id": 219, "type": "essay", "q": "Analyze the design and determine which digital art elements are effectively used", "a": "Color, typography, layout, contrast, and spacing are used effectively." },
  { "id": 220, "type": "essay", "q": "Look at a design where all text has the same size and style. What is the problem and how can it be improved?", "a": "No visual hierarchy, Hard to know what is important, Improve by changing size, weight, spacing" }
];