const allQuestionsData = [
{ id: 1, type: "tf", q: "(True or False) Artificial Intelligence is a system designed to think exactly like a human mind.", a: "false" },
                { id: 2, type: "tf", q: "(True or False) The confidence score shows how strongly the AI believes in its prediction.", a: "true" },
                { id: 3, type: "tf", q: "(True or False) A digital image is a grid of tiny squares called pixels.", a: "true" },
                { id: 4, type: "tf", q: "(True or False) Image classification assigns a single label to an entire image.", a: "true" },
                { id: 5, type: "tf", q: "(True or False) Face detection and face recognition are the same task.", a: "false" },
                { id: 6, type: "tf", q: "(True or False) A false positive in a face unlock system means the system let in an unauthorized person.", a: "true" },
                { id: 7, type: "tf", q: "(True or False) Background noise does not affect speech recognition accuracy.", a: "false" },
                { id: 8, type: "tf", q: "(True or False) Language models generate responses by predicting the most likely next word.", a: "true" },
                { id: 9, type: "tf", q: "(True or False) Real-time systems require processing input and producing output instantly.", a: "true" },
                { id: 10, type: "tf", q: "(True or False) If one keypoint is incorrect, it can affect the detection of connected joints.", a: "true" },

                // --- Multiple Choice (11-18) ---
                { id: 11, type: "mcq", q: "What is the main difference between AI and traditional software?", opts: ["AI uses more electricity", "AI learns patterns from data, while traditional software follows fixed rules", "Traditional software is faster", "AI is always correct"], a: "AI learns patterns from data, while traditional software follows fixed rules" },
                { id: 12, type: "mcq", q: "What does an AI model output when it analyzes an image?", opts: ["A guaranteed answer", "A prediction with a confidence score", "A random guess", "The name of the person who took the image"], a: "A prediction with a confidence score" },
                { id: 13, type: "mcq", q: "Which of the following is an example of a correlation, not causation?", opts: ["Rain causes wet ground", "A fire causes smoke", "Ice cream sales and hot weather increase together", "Pressing a light switch turns on a bulb"], a: "Ice cream sales and hot weather increase together" },
                { id: 14, type: "mcq", q: "What does a confidence score of 95% mean?", opts: ["The answer is 95% wrong", "The answer is guaranteed to be correct", "The AI is 95% sure about its prediction", "The AI has no idea what the object is"], a: "The AI is 95% sure about its prediction" },
                { id: 15, type: "mcq", q: "What is a pixel?", opts: ["A color in the image", "A tiny square that holds a numeric value for brightness or color", "The shape of an object", "The name of an AI model"], a: "A tiny square that holds a numeric value for brightness or color" },
                { id: 16, type: "mcq", q: "Which task answers the question 'What objects are in this image, and where are they?'", opts: ["Image Classification", "Object Detection", "Face Recognition", "Pose Estimation"], a: "Object Detection" },
                { id: 17, type: "mcq", q: "A bounding box is used to:", opts: ["Draw a rectangle around a detected object", "Label the entire image", "Show the confidence score", "Remove noise from the image"], a: "Draw a rectangle around a detected object" },
                { id: 18, type: "mcq", q: "Which task is about finding the location of a face in an image?", opts: ["Face Recognition", "Face Detection", "Face Verification", "Face Identification"], a: "Face Detection" },

                // --- Short Answer / Essay (19-60) ---
                { id: 19, type: "essay", q: "Define Artificial Intelligence in your own words.", a: "AI is a system that can learn from data and make predictions, rather than just following fixed rules." },
                { id: 20, type: "essay", q: "What is the main difference between a traditional program and an AI system?", a: "A traditional program follows fixed rules written by a programmer, while an AI learns patterns from data." },
                { id: 21, type: "essay", q: "List the five steps of how AI answers an input (Image or Data).", a: "1. Input, 2. Processing, 3. Pattern Recognition, 4. Prediction, 5. Output." },
                { id: 22, type: "essay", q: "Define the term 'correlation'.", a: "Correlation is when two things appear together frequently in data, but it doesn't mean one causes the other." },
                { id: 23, type: "essay", q: "Give an example of a correlation that is not a direct cause.", a: "Ice cream sales and hot weather increase together." },
                { id: 24, type: "essay", q: "What is a confidence score in AI?", a: "A percentage that shows how strongly the AI believes in its prediction." },
                { id: 25, type: "essay", q: "Mention the three types of AI.", a: "Artificial Narrow Intelligence (ANI), Artificial General Intelligence (AGI), and Artificial Super Intelligence (ASI)." },
                { id: 26, type: "essay", q: "List the main components of the Core AI Learning Workflow.", a: "Data, Training, Model, Prediction." },
                { id: 27, type: "essay", q: "Define 'overfitting'.", a: "Overfitting occurs when a model learns the training data too specifically, memorizing details and noise, so it fails on new data." },
                { id: 28, type: "essay", q: "Define 'underfitting'.", a: "Underfitting happens when a model is too simple to capture the meaningful patterns in the data." },
                { id: 29, type: "essay", q: "What is the difference between a false positive and a false negative?", a: "A false positive is when the system says 'yes' but the answer is 'no.' A false negative is when the system says 'no' but the answer is 'yes.'" },
                { id: 30, type: "essay", q: "What is the function of validation data?", a: "Validation data is used to test a model's performance on new, unseen data to ensure it has learned general patterns and not just memorized the training data." },
                { id: 31, type: "essay", q: "Mention the two main stages of machine learning.", a: "Training and Prediction (Inference)." },
                { id: 32, type: "essay", q: "What is the 'Black Box Problem'?", a: "It's the difficulty of understanding exactly how an AI system arrives at a decision because of its internal complexity." },
                { id: 33, type: "essay", q: "What is the main cause of a model underfitting?", a: "The model is too simple or hasn't been trained on enough data to capture the patterns." },
                { id: 34, type: "essay", q: "List the three main types of machine learning.", a: "Supervised Learning, Unsupervised Learning, Reinforcement Learning." },
                { id: 35, type: "essay", q: "What is the difference between training and prediction (inference)?", a: "During training, the model learns by adjusting its parameters. During prediction, the model uses its learned parameters to make decisions on new data." },
                { id: 36, type: "essay", q: "What is a digital image composed of?", a: "A digital image is composed of a grid of tiny squares called pixels, each containing a numeric value." },
                { id: 37, type: "essay", q: "Define 'pixel'.", a: "A pixel is the smallest unit of a digital image, which holds a number representing brightness or color." },
                { id: 38, type: "essay", q: "In a grayscale image, what does a pixel value of 255 represent?", a: "white" },
                { id: 39, type: "essay", q: "What are the three color channels in a digital image?", a: "Red, Green, and Blue (RGB)." },
                { id: 40, type: "essay", q: "List the main tasks of a Computer Vision system mentioned in the lesson.", a: "Image Classification, Object Detection, Face Detection/Recognition, Pose Estimation." },
                { id: 41, type: "essay", q: "What is the purpose of image classification?", a: "To assign one label to an entire image." },
                { id: 42, type: "essay", q: "How does object detection differ from image classification?", a: "Object detection identifies multiple objects and their locations (using bounding boxes), while classification gives one label for the whole image." },
                { id: 43, type: "essay", q: "Define 'bounding box'.", a: "A rectangle drawn around a detected object to show its location." },
                { id: 44, type: "essay", q: "Give an example of a vision failure case.", a: "Motion blur, occlusion, or poor lighting that causes the AI to misclassify an object." },
                { id: 45, type: "essay", q: "What is the semantic gap?", a: "The difference between the raw numeric data (pixels) that an AI processes and the human understanding of an image's meaning." },
                { id: 46, type: "essay", q: "Define 'occlusion'.", a: "When part of an object is blocked or hidden from view." },
                { id: 47, type: "essay", q: "What is the function of bounding boxes in object detection?", a: "To localize where an object is within an image." },
                { id: 48, type: "essay", q: "Define the difference between face detection and face recognition.", a: "Face detection finds the location of a face, while face recognition identifies whose face it is." },
                { id: 49, type: "essay", q: "What is the purpose of face detection?", a: "To determine if there is a face in an image and where it is located." },
                { id: 50, type: "essay", q: "What is the function of facial landmarks?", a: "They are specific key points on the face (like eyes, nose, mouth) that help describe its structure." },
                { id: 51, type: "essay", q: "List the two main modes of face recognition.", a: "Verification (1:1) and Identification (1:N)." },
                { id: 52, type: "essay", q: "What is a false positive in a face unlock system?", a: "The system grants access to someone who is not authorized." },
                { id: 53, type: "essay", q: "Mention the two main error types in AI systems.", a: "False Positive and False Negative." },
                { id: 54, type: "essay", q: "What is a false negative in a face unlock system?", a: "The system denies access to the authorized user." },
                { id: 55, type: "essay", q: "What is a threshold in a face recognition system?", a: "A chosen confidence level that decides whether the system accepts or rejects a match." },
                { id: 56, type: "essay", q: "What is the main cause of bias in AI?", a: "Bias is usually a data problem, caused by training data that is incomplete, unbalanced, or not representative of the real world." },
                { id: 57, type: "essay", q: "What is a spoofing attack?", a: "An attempt to trick a face recognition system, for example, by using a printed photo or a mask." },
                { id: 58, type: "essay", q: "Define 'liveness detection'.", a: "A technology used to check if a face is from a real, live person (e.g., by asking the user to blink) and not a spoof." },
                { id: 59, type: "essay", q: "What is the purpose of alignment in face recognition?", a: "To standardize a face (rotate, scale, center) so that the system compares normalized faces and not camera angles or positions." },
                { id: 60, type: "essay", q: "What is the difference between verification and identification?", a: "Verification is a 1:1 comparison (is this you?), while identification is a 1:N comparison (who is this?)." },

                // --- TPKA2: Design AI (61-66 TF) ---
                { id: 61, type: "tf", q: "(True or False) In traditional software, the same input always produces the same output.", a: "true" },
                { id: 62, type: "tf", q: "(True or False) The 'Black Box Problem' refers to the difficulty of explaining how an AI makes a decision.", a: "true" },
                { id: 63, type: "tf", q: "(True or False) In a grayscale image, a pixel value of 255 represents black.", a: "false" },
                { id: 64, type: "tf", q: "(True or False) Higher resolution images always lead to faster processing for AI models.", a: "false" },
                { id: 65, type: "tf", q: "(True or False) Latency is the time delay between an action and the system's response.", a: "true" },
                { id: 66, type: "tf", q: "(True or False) OCR works best when there is high contrast between the text and its background.", a: "true" },

                // --- TPKA2: MCQ (67-76) ---
                { id: 67, type: "mcq", q: "In a grayscale image, what does a pixel value of 0 represent?", opts: ["White", "Black", "Gray", "Red"], a: "Black" },
                { id: 68, type: "mcq", q: "In face recognition, what is an embedding?", opts: ["A picture of a face", "A numerical vector that represents a face", "A bounding box around a face", "The confidence score"], a: "A numerical vector that represents a face" },
                { id: 69, type: "mcq", q: "Which process compares one live face to one stored reference?", opts: ["Identification (1:N)", "Classification", "Verification (1:1)", "Detection"], a: "Verification (1:1)" },
                { id: 70, type: "mcq", q: "What is the purpose of liveness detection?", opts: ["To increase confidence scores", "To detect if a face is from a real person or a spoof (like a photo)", "To improve image resolution", "To make the AI faster"], a: "To detect if a face is from a real person or a spoof (like a photo)" },
                { id: 71, type: "mcq", q: "What is 'latency' in a real-time system?", opts: ["The speed of the internet connection", "The number of frames per second", "The delay between an action and the system's response", "The accuracy of the prediction"], a: "The delay between an action and the system's response" },
                { id: 72, type: "mcq", q: "What does NLP stand for?", opts: ["Neural Language Programming", "Natural Language Processing", "Numeric Linguistic Protocol", "Non-linear Prediction"], a: "Natural Language Processing" },
                { id: 73, type: "mcq", q: "What is the main function of Optical Character Recognition (OCR)?", opts: ["To convert images of characters into digital text", "To understand the meaning of a sentence", "To convert spoken words into text", "To recognize faces in an image"], a: "To convert images of characters into digital text" },
                { id: 74, type: "mcq", q: "Why can speech recognition fail in a noisy room?", opts: ["Because the AI stops listening", "Because noise distorts the sound patterns the AI is trained on", "Because the AI only understands text", "Because the microphone turns off"], a: "Because noise distorts the sound patterns the AI is trained on" },
                { id: 75, type: "mcq", q: "Which type of AI is designed to perform one specific task only?", opts: ["Artificial General Intelligence (AGI)", "Artificial Super Intelligence (ASI)", "Artificial Narrow Intelligence (ANI)", "All of the above"], a: "Artificial Narrow Intelligence (ANI)" },
                { id: 76, type: "mcq", q: "What is the first step in the AI learning workflow?", opts: ["Prediction", "Data (Training Data)", "Model", "Output"], a: "Data (Training Data)" },

                // --- Short Answer Group 5 (77-96) ---
                { id: 77, type: "essay", q: "Define pose estimation.", a: "The process of detecting key points on the human body (like joints) and connecting them to form a skeletal structure." },
                { id: 78, type: "essay", q: "What is a keypoint in pose estimation?", a: "A coordinate point on the body that represents a joint, such as a shoulder, elbow, or knee." },
                { id: 79, type: "essay", q: "List some of the keypoints detected by a pose estimation system.", a: "Nose, shoulders, elbows, wrists, hips, knees, ankles." },
                { id: 80, type: "essay", q: "How is the human body modeled in pose estimation?", a: "As a graph, where nodes are keypoints and edges are the connections between them." },
                { id: 81, type: "essay", q: "What is the difference between a static pose and a dynamic gesture?", a: "A static pose is one frame of body coordinates, while a dynamic gesture is a pattern across multiple frames." },
                { id: 82, type: "essay", q: "What is 'temporal consistency' in gesture recognition?", a: "The requirement that a gesture's movement pattern must be detected across several consecutive frames to be confirmed." },
                { id: 83, type: "essay", q: "Define 'latency' in a real-time system.", a: "The delay between an action (like a gesture) and the system's response." },
                { id: 84, type: "essay", q: "Define 'dropped frames' and their effect on gesture recognition.", a: "Dropped frames are skipped images. They can break the temporal sequence needed to recognize a gesture, causing a false negative." },
                { id: 85, type: "essay", q: "What is the difference between spatial and temporal instability?", a: "Spatial instability is jitter in a single frame's keypoints. Temporal instability is inconsistency in keypoints from frame to frame." },
                { id: 86, type: "essay", q: "Define speech recognition.", a: "The technology that converts spoken language into written text." },
                { id: 87, type: "essay", q: "What is the main function of OCR (Optical Character Recognition)?", a: "To convert images of text (printed or handwritten) into digital, machine-readable text." },
                { id: 88, type: "essay", q: "What is OCR stands for?", a: "Optical Character Recognition" },
                { id: 89, type: "essay", q: "Define NLP (Natural Language Processing).", a: "The field of AI that allows computers to work with, interpret, and approximate meaning from human language" },
                { id: 90, type: "essay", q: "List the typical steps a voice assistant follows.", a: "1. Speech Recognition, 2. Natural Language Processing (NLP), 3. System Action." },
                { id: 91, type: "essay", q: "Why is speech recognition affected by background noise?", a: "Background noise distorts the sound patterns that the AI has learned to recognize, making it harder to match the audio to the correct words." },
                { id: 92, type: "essay", q: "How does OCR interpret an image of text?", a: "It detects shapes (clusters of pixels) and matches them to learned character patterns (like letters or numbers)." },
                { id: 93, type: "essay", q: "Provide one example that shows a limitation of NLP systems.", a: "An NLP system may misunderstand a rare or unusual phrasing of a command because it hasn't seen that pattern in its training data." },
                { id: 94, type: "essay", q: "What is the purpose of tokenization in NLP?", a: "To break down a sentence into smaller, processable units (like words or parts of words) so the computer can analyze them." },
                { id: 95, type: "essay", q: "What is the main cause of OCR errors?", a: "Poor image quality, such as low contrast, blurriness, unusual fonts, or poor lighting, which makes it hard to distinguish characters." },
                { id: 96, type: "essay", q: "What is the function of confidence scores in speech recognition?", a: "To show how likely the system thinks its transcribed words are correct, based on the sound patterns it detected." },

                // --- Comparison Group 6 (97-113) ---
                { id: 97, type: "essay", q: "Compare traditional software and artificial intelligence.", a: "Traditional software follows fixed rules written by a programmer, while AI learns patterns from data." },
                { id: 98, type: "essay", q: "Compare correlation and causation.", a: "Correlation means two things appear together frequently; causation means one thing directly causes another." },
                { id: 99, type: "essay", q: "Compare automation and intelligence.", a: "Automation follows fixed rules (deterministic), while intelligence learns from data and adapts (probabilistic)." },
                { id: 100, type: "essay", q: "Compare training and prediction (inference).", a: "Training is when the system learns from data; prediction is when the system uses what it learned." },
                { id: 101, type: "essay", q: "Compare overfitting and underfitting.", a: "Overfitting is when a model learns training data too specifically; underfitting is when a model is too simple to learn patterns." },
                { id: 102, type: "essay", q: "Compare a false positive and a false negative.", a: "A false positive says 'yes' when the answer is 'no'; a false negative says 'no' when the answer is 'yes.'" },
                { id: 103, type: "essay", q: "Compare supervised learning and unsupervised learning.", a: "Supervised learning uses labeled data (with answers); unsupervised learning uses unlabeled data (finds patterns on its own)." },
                { id: 104, type: "essay", q: "Compare Narrow AI (ANI) and General AI (AGI).", a: "Narrow AI performs one specific task; General AI can perform many different tasks like a human (does not exist yet)." },
                { id: 105, type: "essay", q: "Compare how humans see images and how AI sees images.", a: "Humans see meaning, colors, and objects; AI sees a grid of numbers (pixels) representing brightness and color." },
                { id: 106, type: "essay", q: "Compare a color image and a grayscale image in terms of data.", a: "A color image has three matrices (RGB channels); a grayscale image has one matrix (brightness only)." },
                { id: 107, type: "essay", q: "Compare image classification and object detection.", a: "Classification assigns one label to the whole image; detection finds multiple objects and their locations with bounding boxes." },
                { id: 108, type: "essay", q: "Compare high-resolution and low-resolution images for AI processing.", a: "High-resolution images have more detail but take more computation; low-resolution images are faster but may lose important details." },
                { id: 109, type: "essay", q: "Compare face detection and face recognition.", a: "Face detection finds where a face is; face recognition identifies whose face it is." },
                { id: 110, type: "essay", q: "Compare pose estimation and face detection.", a: "Pose estimation detects body keypoints (shoulders, knees); face detection only finds faces." },
                { id: 111, type: "essay", q: "Compare speech recognition and OCR.", a: "Speech recognition converts sound to text; OCR converts images of text to digital text." },
                { id: 112, type: "essay", q: "Compare a rule-based chatbot and an AI-based conversational system.", a: "Rule-based follows fixed scripts; AI-based generates responses using probability." },
                { id: 113, type: "essay", q: "Compare a speech recognition system in a quiet room and in a noisy room.", a: "Quiet room gives high accuracy; noisy room may cause errors due to distorted sound patterns." }];