const allQuestionsData = [
{ "id": 1, "type": "essay", "q": "(Scientific Term) Way of organizing and storing data efficiently.", "a": "Data Structures" },
{ "id": 2, "type": "essay", "q": "(Scientific Term) Step-by-step procedure to solve a problem.", "a": "Algorithm" },
{ "id": 3, "type": "essay", "q": "(Scientific Term) Measure of algorithm performance.", "a": "Complexity" },
{ "id": 4, "type": "essay", "q": "(Scientific Term) Notation used to describe algorithm efficiency.", "a": "Big O Notation" },
{ "id": 5, "type": "essay", "q": "(Short Answer) What is a data structure?", "a": "A way to organize and store data efficiently." },
{ "id": 6, "type": "essay", "q": "(Short Answer) What is an algorithm?", "a": "A step-by-step procedure to solve a problem." },
{ "id": 7, "type": "essay", "q": "(Short Answer) Why are data structures important?", "a": "They improve efficiency of operations." },
{ "id": 8, "type": "essay", "q": "(Short Answer) Why are algorithms important?", "a": "They provide a clear solution method." },
{ "id": 9, "type": "essay", "q": "(Short Answer) What is complexity?", "a": "Measurement of time or space usage." },
{ "id": 10, "type": "essay", "q": "(Short Answer) What is time complexity?", "a": "Time taken relative to input size." },
{ "id": 11, "type": "essay", "q": "(Short Answer) What is space complexity?", "a": "Memory used by algorithm." },
{ "id": 12, "type": "essay", "q": "(Short Answer) Difference between data structure and algorithm?", "a": "DS stores data, algorithm processes it." },
{ "id": 13, "type": "essay", "q": "(Short Answer) What are primitive data structures?", "a": "Basic data types like int, float." },
{ "id": 14, "type": "essay", "q": "(Short Answer) What are non-primitive data structures?", "a": "Complex structures like arrays, lists." },
{ "id": 15, "type": "essay", "q": "(Short Answer) What is efficiency?", "a": "Performance in time and space." },
{ "id": 16, "type": "essay", "q": "(Short Answer) What is scalability?", "a": "Performance with large inputs." },
{ "id": 17, "type": "essay", "q": "(Short Answer) What is input size?", "a": "Amount of data given to algorithm." },
{ "id": 18, "type": "essay", "q": "(Short Answer) What is output?", "a": "Result after processing input." },
{ "id": 19, "type": "essay", "q": "(Short Answer) What is optimization?", "a": "Improving performance." },
{ "id": 20, "type": "essay", "q": "(Short Answer) Why compare algorithms?", "a": "To choose the most efficient one." },
{ "id": 21, "type": "essay", "q": "(Complete) Algorithm consists of [___] steps.", "a": "finite" },
{ "id": 22, "type": "essay", "q": "(Complete) Data structures help [___] data.", "a": "organize" },
{ "id": 23, "type": "essay", "q": "(Complete) Big O measures [___].", "a": "performance" },
{ "id": 24, "type": "essay", "q": "(Complete) Complexity depends on [___].", "a": "input size" },
{ "id": 25, "type": "essay", "q": "(Complete) Algorithms process [___].", "a": "data" },
{ "id": 26, "type": "essay", "q": "(Complete) Efficiency improves [___].", "a": "performance" },
{ "id": 27, "type": "essay", "q": "(Complete) Primitive types include [___].", "a": "integers" },
{ "id": 28, "type": "essay", "q": "(Complete) Output is the [___].", "a": "result" },
{ "id": 29, "type": "essay", "q": "(Complete) Input is the [___].", "a": "data" },
{ "id": 30, "type": "essay", "q": "(Complete) Optimization reduces [___].", "a": "cost" },

{ "id": 31, "type": "tf", "q": "(True or False) An algorithm solves problems step by step.", "a": "true" },
{ "id": 32, "type": "tf", "q": "(True or False) Data structures are only used for storage.", "a": "false" },
{ "id": 33, "type": "tf", "q": "(True or False) Big O describes efficiency.", "a": "true" },
{ "id": 34, "type": "tf", "q": "(True or False) Complexity depends on input size.", "a": "true" },
{ "id": 35, "type": "tf", "q": "(True or False) Algorithms always use same time.", "a": "false" },

{ "id": 36, "type": "mcq", "q": "What is an algorithm?", "opts": ["Data", "Steps to solve problem", "Memory", "Loop"], "a": "Steps to solve problem" },
{ "id": 37, "type": "mcq", "q": "What is a data structure?", "opts": ["Program", "Storage method", "Language", "Loop"], "a": "Storage method" },
{ "id": 38, "type": "mcq", "q": "Big O measures?", "opts": ["Speed", "Memory", "Performance", "All"], "a": "Performance" },
{ "id": 39, "type": "mcq", "q": "Primitive type example?", "opts": ["Array", "Integer", "Tree", "Graph"], "a": "Integer" },
{ "id": 40, "type": "mcq", "q": "Non-primitive example?", "opts": ["Float", "Char", "Array", "Int"], "a": "Array" },
{ "id": 41, "type": "mcq", "q": "Algorithm input is?", "opts": ["Result", "Data", "Output", "Loop"], "a": "Data" },
{ "id": 42, "type": "mcq", "q": "Algorithm output is?", "opts": ["Data", "Loop", "Result", "Memory"], "a": "Result" },
{ "id": 43, "type": "mcq", "q": "Efficiency means?", "opts": ["Speed only", "Memory only", "Performance", "None"], "a": "Performance" },
{ "id": 44, "type": "mcq", "q": "Optimization improves?", "opts": ["Design", "Performance", "Color", "Input"], "a": "Performance" },
{ "id": 45, "type": "mcq", "q": "Complexity depends on?", "opts": ["Color", "Input size", "Font", "Screen"], "a": "Input size" },

{ "id": 46, "type": "essay", "q": "(Short Answer) Why algorithms vary in efficiency?", "a": "Because different approaches use different resources." },
{ "id": 47, "type": "essay", "q": "(Short Answer) Why use Big O?", "a": "To compare algorithm performance." },
{ "id": 48, "type": "essay", "q": "(Short Answer) What is performance?", "a": "Speed and memory usage." },
{ "id": 49, "type": "essay", "q": "(Short Answer) Why analyze complexity?", "a": "To improve efficiency." },
{ "id": 50, "type": "essay", "q": "(Short Answer) What is scalability?", "a": "Handling large input efficiently." },
{ "id": 51, "type": "essay", "q": "(Scientific Term) Fixed-size collection of elements of the same type.", "a": "Array" },
{ "id": 52, "type": "essay", "q": "(Scientific Term) Data structure consisting of nodes connected together.", "a": "Linked List" },
{ "id": 53, "type": "essay", "q": "(Scientific Term) Structure that stores data using key-value pairs.", "a": "Hash Map" },
{ "id": 54, "type": "essay", "q": "(Scientific Term) Reference to the next node in a linked list.", "a": "Pointer" },
{ "id": 55, "type": "essay", "q": "(Short Answer) What is an array?", "a": "A collection of elements stored in contiguous memory." },
{ "id": 56, "type": "essay", "q": "(Short Answer) What is a linked list?", "a": "A structure of nodes connected by pointers." },
{ "id": 57, "type": "essay", "q": "(Short Answer) What is a hash map?", "a": "A data structure storing key-value pairs." },
{ "id": 58, "type": "essay", "q": "(Short Answer) Advantage of arrays?", "a": "Fast access using index." },
{ "id": 59, "type": "essay", "q": "(Short Answer) Disadvantage of arrays?", "a": "Fixed size and costly insertion." },
{ "id": 60, "type": "essay", "q": "(Short Answer) Advantage of linked list?", "a": "Easy insertion and deletion." },
{ "id": 61, "type": "essay", "q": "(Short Answer) Disadvantage of linked list?", "a": "Extra memory for pointers." },
{ "id": 62, "type": "essay", "q": "(Short Answer) Advantage of hash map?", "a": "Fast search using keys." },
{ "id": 63, "type": "essay", "q": "(Short Answer) Disadvantage of hash map?", "a": "Collision handling required." },
{ "id": 64, "type": "essay", "q": "(Short Answer) What is indexing?", "a": "Accessing elements by position." },
{ "id": 65, "type": "essay", "q": "(Short Answer) What is node?", "a": "Element containing data and pointer." },
{ "id": 66, "type": "essay", "q": "(Short Answer) What is pointer?", "a": "Reference to another node." },
{ "id": 67, "type": "essay", "q": "(Short Answer) What is collision in hash map?", "a": "Two keys map to same index." },
{ "id": 68, "type": "essay", "q": "(Short Answer) Difference between array and linked list?", "a": "Array uses contiguous memory, linked list uses pointers." },
{ "id": 69, "type": "essay", "q": "(Short Answer) When to use arrays?", "a": "When fast access is needed." },
{ "id": 70, "type": "essay", "q": "(Short Answer) When to use linked list?", "a": "When frequent insertion is needed." },
{ "id": 71, "type": "essay", "q": "(Complete) Array elements are accessed using [___].", "a": "index" },
{ "id": 72, "type": "essay", "q": "(Complete) Linked list is made of [___].", "a": "nodes" },
{ "id": 73, "type": "essay", "q": "(Complete) Hash map stores [___] pairs.", "a": "key-value" },
{ "id": 74, "type": "essay", "q": "(Complete) Linked list uses [___] to connect nodes.", "a": "pointers" },
{ "id": 75, "type": "essay", "q": "(Complete) Array size is usually [___].", "a": "fixed" },
{ "id": 76, "type": "essay", "q": "(Complete) Linked list memory is [___].", "a": "dynamic" },
{ "id": 77, "type": "essay", "q": "(Complete) Hash map lookup uses [___].", "a": "key" },
{ "id": 78, "type": "essay", "q": "(Complete) Last node points to [___].", "a": "null" },
{ "id": 79, "type": "essay", "q": "(Complete) Collision occurs when keys share same [___].", "a": "index" },
{ "id": 80, "type": "essay", "q": "(Complete) Array elements are stored in [___] memory.", "a": "contiguous" },

{ "id": 81, "type": "tf", "q": "(True or False) Arrays store elements in order.", "a": "true" },
{ "id": 82, "type": "tf", "q": "(True or False) Linked lists use pointers.", "a": "true" },
{ "id": 83, "type": "tf", "q": "(True or False) Hash maps use keys.", "a": "true" },
{ "id": 84, "type": "tf", "q": "(True or False) Arrays allow dynamic resizing automatically.", "a": "false" },
{ "id": 85, "type": "tf", "q": "(True or False) Linked list allows fast random access.", "a": "false" },

{ "id": 86, "type": "mcq", "q": "Array is:", "opts": ["Dynamic", "Fixed-size", "Graph", "Tree"], "a": "Fixed-size" },
{ "id": 87, "type": "mcq", "q": "Linked list stores:", "opts": ["Numbers only", "Nodes", "Keys only", "Indexes"], "a": "Nodes" },
{ "id": 88, "type": "mcq", "q": "Hash map stores:", "opts": ["Values", "Pairs", "Indexes", "Nodes"], "a": "Pairs" },
{ "id": 89, "type": "mcq", "q": "Array access method:", "opts": ["Pointer", "Index", "Key", "Loop"], "a": "Index" },
{ "id": 90, "type": "mcq", "q": "Linked list insertion is:", "opts": ["Hard", "Easy", "Impossible", "Slow"], "a": "Easy" },
{ "id": 91, "type": "mcq", "q": "Hash map search is:", "opts": ["Slow", "Fast", "Random", "Manual"], "a": "Fast" },
{ "id": 92, "type": "mcq", "q": "Pointer stores:", "opts": ["Data", "Address", "Loop", "Index"], "a": "Address" },
{ "id": 93, "type": "mcq", "q": "Collision occurs in:", "opts": ["Array", "Stack", "Hash map", "Queue"], "a": "Hash map" },
{ "id": 94, "type": "mcq", "q": "Linked list memory:", "opts": ["Fixed", "Dynamic", "Static", "None"], "a": "Dynamic" },
{ "id": 95, "type": "mcq", "q": "Array memory:", "opts": ["Random", "Contiguous", "Dynamic", "Linked"], "a": "Contiguous" },

{ "id": 96, "type": "essay", "q": "(Short Answer) Why arrays are fast?", "a": "Because of direct indexing." },
{ "id": 97, "type": "essay", "q": "(Short Answer) Why linked lists use more memory?", "a": "Due to pointers." },
{ "id": 98, "type": "essay", "q": "(Short Answer) Why collisions occur?", "a": "Because multiple keys map to same index." },
{ "id": 99, "type": "essay", "q": "(Short Answer) Why hash maps are efficient?", "a": "Because of fast key lookup." },
{ "id": 100, "type": "essay", "q": "(Short Answer) Why arrays are limited?", "a": "Because of fixed size." },{ "id": 101, "type": "essay", "q": "(Scientific Term) Process of arranging elements in a specific order.", "a": "Sorting" },
{ "id": 102, "type": "essay", "q": "(Scientific Term) Algorithm that compares adjacent elements and swaps them.", "a": "Bubble Sort" },
{ "id": 103, "type": "essay", "q": "(Scientific Term) Algorithm that selects the smallest element repeatedly.", "a": "Selection Sort" },
{ "id": 104, "type": "essay", "q": "(Scientific Term) Algorithm that inserts elements into sorted position.", "a": "Insertion Sort" },
{ "id": 105, "type": "essay", "q": "(Scientific Term) Process of finding a specific element.", "a": "Searching" },

{ "id": 106, "type": "essay", "q": "(Short Answer) What is sorting?", "a": "Arranging elements in order." },
{ "id": 107, "type": "essay", "q": "(Short Answer) Why is sorting important?", "a": "To make searching and processing easier." },
{ "id": 108, "type": "essay", "q": "(Short Answer) What is selection sort?", "a": "Selecting smallest element and placing it correctly." },
{ "id": 109, "type": "essay", "q": "(Short Answer) What is bubble sort?", "a": "Swapping adjacent elements repeatedly." },
{ "id": 110, "type": "essay", "q": "(Short Answer) What is insertion sort?", "a": "Inserting element into sorted part." },

{ "id": 111, "type": "essay", "q": "(Short Answer) Difference between sorting and searching?", "a": "Sorting arranges data, searching finds data." },
{ "id": 112, "type": "essay", "q": "(Short Answer) When is bubble sort useful?", "a": "Small datasets." },
{ "id": 113, "type": "essay", "q": "(Short Answer) When is insertion sort useful?", "a": "Nearly sorted data." },
{ "id": 114, "type": "essay", "q": "(Short Answer) When is selection sort useful?", "a": "Simple implementation cases." },
{ "id": 115, "type": "essay", "q": "(Short Answer) What is key in insertion sort?", "a": "Element being inserted." },

{ "id": 116, "type": "essay", "q": "(Short Answer) Why sorting improves search?", "a": "Because ordered data is easier to locate." },
{ "id": 117, "type": "essay", "q": "(Short Answer) What is comparison in sorting?", "a": "Checking order between elements." },
{ "id": 118, "type": "essay", "q": "(Short Answer) What is swapping?", "a": "Exchanging positions of elements." },
{ "id": 119, "type": "essay", "q": "(Short Answer) What is iteration?", "a": "Repeating steps." },
{ "id": 120, "type": "essay", "q": "(Short Answer) What is pass in sorting?", "a": "One full cycle through data." },

{ "id": 121, "type": "essay", "q": "(Complete) Sorting arranges data in [___] order.", "a": "ascending" },
{ "id": 122, "type": "essay", "q": "(Complete) Bubble sort compares [___] elements.", "a": "adjacent" },
{ "id": 123, "type": "essay", "q": "(Complete) Selection sort selects [___] element.", "a": "smallest" },
{ "id": 124, "type": "essay", "q": "(Complete) Insertion sort inserts into [___] portion.", "a": "sorted" },
{ "id": 125, "type": "essay", "q": "(Complete) Searching finds [___] element.", "a": "specific" },

{ "id": 126, "type": "essay", "q": "(Complete) Bubble sort uses [___] operation.", "a": "swap" },
{ "id": 127, "type": "essay", "q": "(Complete) Sorting improves [___] efficiency.", "a": "searching" },
{ "id": 128, "type": "essay", "q": "(Complete) Selection sort finds [___] value.", "a": "minimum" },
{ "id": 129, "type": "essay", "q": "(Complete) Insertion sort shifts [___].", "a": "elements" },
{ "id": 130, "type": "essay", "q": "(Complete) Sorting algorithms use [___].", "a": "comparisons" },

{ "id": 131, "type": "tf", "q": "(True or False) Sorting arranges data.", "a": "true" },
{ "id": 132, "type": "tf", "q": "(True or False) Bubble sort compares adjacent elements.", "a": "true" },
{ "id": 133, "type": "tf", "q": "(True or False) Selection sort selects largest first always.", "a": "false" },
{ "id": 134, "type": "tf", "q": "(True or False) Insertion sort builds sorted list gradually.", "a": "true" },
{ "id": 135, "type": "tf", "q": "(True or False) Sorting is only for numbers.", "a": "false" },

{ "id": 136, "type": "mcq", "q": "Which algorithm swaps adjacent elements?", "opts": ["Selection", "Insertion", "Bubble", "Search"], "a": "Bubble" },
{ "id": 137, "type": "mcq", "q": "Which algorithm selects smallest element?", "opts": ["Bubble", "Insertion", "Selection", "Linear"], "a": "Selection" },
{ "id": 138, "type": "mcq", "q": "Insertion sort works by:", "opts": ["Swapping", "Selecting", "Inserting", "Deleting"], "a": "Inserting" },
{ "id": 139, "type": "mcq", "q": "Sorting helps in:", "opts": ["Deleting", "Searching", "Printing", "Looping"], "a": "Searching" },
{ "id": 140, "type": "mcq", "q": "Sorting arranges data in:", "opts": ["Random", "Order", "Loop", "None"], "a": "Order" },

{ "id": 141, "type": "mcq", "q": "Bubble sort compares:", "opts": ["All elements", "Adjacent", "Random", "Middle"], "a": "Adjacent" },
{ "id": 142, "type": "mcq", "q": "Selection sort finds:", "opts": ["Max", "Min", "Both", "None"], "a": "Min" },
{ "id": 143, "type": "mcq", "q": "Insertion sort inserts:", "opts": ["At end", "Correct position", "Random", "Start"], "a": "Correct position" },
{ "id": 144, "type": "mcq", "q": "Searching means:", "opts": ["Arrange", "Find", "Delete", "Swap"], "a": "Find" },
{ "id": 145, "type": "mcq", "q": "Sorting improves:", "opts": ["Memory", "Search speed", "Color", "Loop"], "a": "Search speed" },

{ "id": 146, "type": "essay", "q": "(Short Answer) Why bubble sort is slow?", "a": "Because it uses many comparisons." },
{ "id": 147, "type": "essay", "q": "(Short Answer) Why insertion sort is efficient for small data?", "a": "Because fewer shifts are needed." },
{ "id": 148, "type": "essay", "q": "(Short Answer) Why selection sort is simple?", "a": "Because it uses basic logic." },
{ "id": 149, "type": "essay", "q": "(Short Answer) Why sorting algorithms differ?", "a": "Because of different strategies." },
{ "id": 150, "type": "essay", "q": "(Short Answer) Why sorting is needed in programming?", "a": "To improve efficiency and organization." },
{ "id": 151, "type": "essay", "q": "(Scientific Term) Data structure that follows Last In First Out.", "a": "Stack" },
{ "id": 152, "type": "essay", "q": "(Scientific Term) Data structure that follows First In First Out.", "a": "Queue" },
{ "id": 153, "type": "essay", "q": "(Scientific Term) Hierarchical data structure of nodes.", "a": "Tree" },
{ "id": 154, "type": "essay", "q": "(Scientific Term) Operation used to add element in stack.", "a": "Push" },
{ "id": 155, "type": "essay", "q": "(Scientific Term) Operation used to remove element from stack.", "a": "Pop" },

{ "id": 156, "type": "essay", "q": "(Short Answer) What is a stack?", "a": "A data structure that follows LIFO." },
{ "id": 157, "type": "essay", "q": "(Short Answer) What is a queue?", "a": "A data structure that follows FIFO." },
{ "id": 158, "type": "essay", "q": "(Short Answer) What is a tree?", "a": "A hierarchical data structure." },
{ "id": 159, "type": "essay", "q": "(Short Answer) What is push operation?", "a": "Adding element to stack." },
{ "id": 160, "type": "essay", "q": "(Short Answer) What is pop operation?", "a": "Removing element from stack." },

{ "id": 161, "type": "essay", "q": "(Short Answer) What is enqueue?", "a": "Adding element to queue." },
{ "id": 162, "type": "essay", "q": "(Short Answer) What is dequeue?", "a": "Removing element from queue." },
{ "id": 163, "type": "essay", "q": "(Short Answer) Difference between stack and queue?", "a": "Stack is LIFO, Queue is FIFO." },
{ "id": 164, "type": "essay", "q": "(Short Answer) What is root node?", "a": "Top node of tree." },
{ "id": 165, "type": "essay", "q": "(Short Answer) What is leaf node?", "a": "Node with no children." },

{ "id": 166, "type": "essay", "q": "(Short Answer) What is edge in tree?", "a": "Connection between nodes." },
{ "id": 167, "type": "essay", "q": "(Short Answer) What is depth?", "a": "Distance from root to node." },
{ "id": 168, "type": "essay", "q": "(Short Answer) What is height?", "a": "Distance from node to leaf." },
{ "id": 169, "type": "essay", "q": "(Short Answer) Advantage of stack?", "a": "Easy undo operations." },
{ "id": 170, "type": "essay", "q": "(Short Answer) Advantage of queue?", "a": "Maintains order." },

{ "id": 171, "type": "essay", "q": "(Short Answer) Advantage of tree?", "a": "Efficient hierarchical representation." },
{ "id": 172, "type": "essay", "q": "(Short Answer) What is traversal?", "a": "Visiting nodes in tree." },
{ "id": 173, "type": "essay", "q": "(Short Answer) What is parent node?", "a": "Node with children." },
{ "id": 174, "type": "essay", "q": "(Short Answer) What is child node?", "a": "Node connected below parent." },
{ "id": 175, "type": "essay", "q": "(Short Answer) What is subtree?", "a": "Part of a tree." },

{ "id": 176, "type": "essay", "q": "(Complete) Stack follows [___].", "a": "LIFO" },
{ "id": 177, "type": "essay", "q": "(Complete) Queue follows [___].", "a": "FIFO" },
{ "id": 178, "type": "essay", "q": "(Complete) Top of stack is [___] element.", "a": "last inserted" },
{ "id": 179, "type": "essay", "q": "(Complete) Front of queue is [___] element.", "a": "first inserted" },
{ "id": 180, "type": "essay", "q": "(Complete) Tree consists of [___] and edges.", "a": "nodes" },

{ "id": 181, "type": "tf", "q": "(True or False) Stack uses FIFO.", "a": "false" },
{ "id": 182, "type": "tf", "q": "(True or False) Queue uses FIFO.", "a": "true" },
{ "id": 183, "type": "tf", "q": "(True or False) Tree root is the top node.", "a": "true" },
{ "id": 184, "type": "tf", "q": "(True or False) Leaf node has children.", "a": "false" },
{ "id": 185, "type": "tf", "q": "(True or False) Stack operations are push and pop.", "a": "true" },

{ "id": 186, "type": "mcq", "q": "Stack works as:", "opts": ["FIFO", "LIFO", "Both", "None"], "a": "LIFO" },
{ "id": 187, "type": "mcq", "q": "Queue works as:", "opts": ["FIFO", "LIFO", "Both", "None"], "a": "FIFO" },
{ "id": 188, "type": "mcq", "q": "Top node in tree is:", "opts": ["Leaf", "Root", "Edge", "Branch"], "a": "Root" },
{ "id": 189, "type": "mcq", "q": "Node without children is:", "opts": ["Root", "Leaf", "Edge", "Parent"], "a": "Leaf" },
{ "id": 190, "type": "mcq", "q": "Push operation adds to:", "opts": ["Bottom", "Top", "Middle", "None"], "a": "Top" },

{ "id": 191, "type": "mcq", "q": "Pop operation removes from:", "opts": ["Top", "Bottom", "Middle", "Front"], "a": "Top" },
{ "id": 192, "type": "mcq", "q": "Enqueue adds to:", "opts": ["Front", "Rear", "Top", "Bottom"], "a": "Rear" },
{ "id": 193, "type": "mcq", "q": "Dequeue removes from:", "opts": ["Front", "Rear", "Top", "Middle"], "a": "Front" },
{ "id": 194, "type": "mcq", "q": "Tree consists of:", "opts": ["Nodes", "Edges", "Both", "None"], "a": "Both" },
{ "id": 195, "type": "mcq", "q": "Edge connects:", "opts": ["Nodes", "Arrays", "Loops", "Keys"], "a": "Nodes" },

{ "id": 196, "type": "essay", "q": "(Short Answer) Why stack is useful?", "a": "Used in undo operations." },
{ "id": 197, "type": "essay", "q": "(Short Answer) Why queue is useful?", "a": "Used in scheduling tasks." },
{ "id": 198, "type": "essay", "q": "(Short Answer) Why tree is useful?", "a": "Represents hierarchy." },
{ "id": 199, "type": "essay", "q": "(Short Answer) Why traversal is needed?", "a": "To visit all nodes." },
{ "id": 200, "type": "essay", "q": "(Short Answer) Why root node is important?", "a": "It is starting point of tree." },
{ "id": 201, "type": "essay", "q": "(Scientific Term) Tree where each node has at most two children.", "a": "Binary Tree" },
{ "id": 202, "type": "essay", "q": "(Scientific Term) Data structure representing relationships using nodes and edges.", "a": "Graph" },
{ "id": 203, "type": "essay", "q": "(Scientific Term) Searching algorithm that divides data into halves.", "a": "Binary Search" },
{ "id": 204, "type": "essay", "q": "(Scientific Term) Node with no children in binary tree.", "a": "Leaf" },
{ "id": 205, "type": "essay", "q": "(Scientific Term) Top node of a binary tree.", "a": "Root" },

{ "id": 206, "type": "essay", "q": "(Short Answer) What is a binary tree?", "a": "A tree where each node has at most two children." },
{ "id": 207, "type": "essay", "q": "(Short Answer) What is a graph?", "a": "A set of nodes connected by edges." },
{ "id": 208, "type": "essay", "q": "(Short Answer) What is binary search?", "a": "A search algorithm that divides sorted data into halves." },
{ "id": 209, "type": "essay", "q": "(Short Answer) What is a node in graph?", "a": "A point representing data." },
{ "id": 210, "type": "essay", "q": "(Short Answer) What is an edge?", "a": "A connection between nodes." },

{ "id": 211, "type": "essay", "q": "(Short Answer) What is a leaf node?", "a": "A node with no children." },
{ "id": 212, "type": "essay", "q": "(Short Answer) What is root node?", "a": "Top node of the tree." },
{ "id": 213, "type": "essay", "q": "(Short Answer) What is parent node?", "a": "A node that has children." },
{ "id": 214, "type": "essay", "q": "(Short Answer) What is child node?", "a": "A node connected below parent." },
{ "id": 215, "type": "essay", "q": "(Short Answer) What is traversal?", "a": "Visiting nodes in structure." },

{ "id": 216, "type": "essay", "q": "(Short Answer) What is binary search requirement?", "a": "Data must be sorted." },
{ "id": 217, "type": "essay", "q": "(Short Answer) Advantage of binary search?", "a": "Faster than linear search." },
{ "id": 218, "type": "essay", "q": "(Short Answer) What is graph used for?", "a": "Represent relationships." },
{ "id": 219, "type": "essay", "q": "(Short Answer) What is directed graph?", "a": "Graph with directed edges." },
{ "id": 220, "type": "essay", "q": "(Short Answer) What is undirected graph?", "a": "Graph with no direction edges." },

{ "id": 221, "type": "essay", "q": "(Complete) Binary tree has maximum [___] children.", "a": "two" },
{ "id": 222, "type": "essay", "q": "(Complete) Graph consists of [___] and edges.", "a": "nodes" },
{ "id": 223, "type": "essay", "q": "(Complete) Binary search requires [___] data.", "a": "sorted" },
{ "id": 224, "type": "essay", "q": "(Complete) Binary search checks [___] element first.", "a": "middle" },
{ "id": 225, "type": "essay", "q": "(Complete) Leaf node has [___] children.", "a": "no" },

{ "id": 226, "type": "essay", "q": "(Complete) Root node is at [___] of tree.", "a": "top" },
{ "id": 227, "type": "essay", "q": "(Complete) Edge connects two [___].", "a": "nodes" },
{ "id": 228, "type": "essay", "q": "(Complete) Binary search divides data into [___].", "a": "halves" },
{ "id": 229, "type": "essay", "q": "(Complete) Graph can represent [___].", "a": "relationships" },
{ "id": 230, "type": "essay", "q": "(Complete) Binary tree is a type of [___].", "a": "tree" },

{ "id": 231, "type": "tf", "q": "(True or False) Binary tree can have more than two children.", "a": "false" },
{ "id": 232, "type": "tf", "q": "(True or False) Binary search requires sorted data.", "a": "true" },
{ "id": 233, "type": "tf", "q": "(True or False) Graphs represent relationships.", "a": "true" },
{ "id": 234, "type": "tf", "q": "(True or False) Leaf node has children.", "a": "false" },
{ "id": 235, "type": "tf", "q": "(True or False) Root is the top node.", "a": "true" },

{ "id": 236, "type": "mcq", "q": "Binary tree node can have:", "opts": ["1", "2", "3", "Unlimited"], "a": "2" },
{ "id": 237, "type": "mcq", "q": "Binary search works on:", "opts": ["Unsorted", "Sorted", "Random", "Empty"], "a": "Sorted" },
{ "id": 238, "type": "mcq", "q": "Graph is made of:", "opts": ["Nodes only", "Edges only", "Nodes and edges", "None"], "a": "Nodes and edges" },
{ "id": 239, "type": "mcq", "q": "Leaf node has:", "opts": ["Children", "No children", "Edges", "Root"], "a": "No children" },
{ "id": 240, "type": "mcq", "q": "Binary search checks:", "opts": ["First", "Last", "Middle", "Random"], "a": "Middle" },

{ "id": 241, "type": "mcq", "q": "Graph example:", "opts": ["Array", "Tree", "Road map", "Stack"], "a": "Road map" },
{ "id": 242, "type": "mcq", "q": "Root node is:", "opts": ["Bottom", "Top", "Middle", "Leaf"], "a": "Top" },
{ "id": 243, "type": "mcq", "q": "Binary search reduces size by:", "opts": ["Half", "Double", "Zero", "One"], "a": "Half" },
{ "id": 244, "type": "mcq", "q": "Edge connects:", "opts": ["Arrays", "Nodes", "Graphs", "Trees"], "a": "Nodes" },
{ "id": 245, "type": "mcq", "q": "Graph direction:", "opts": ["Directed", "Undirected", "Both", "None"], "a": "Both" },

{ "id": 246, "type": "essay", "q": "(Short Answer) Why binary search is efficient?", "a": "Because it divides data into halves." },
{ "id": 247, "type": "essay", "q": "(Short Answer) Why graph is useful?", "a": "Represents relationships clearly." },
{ "id": 248, "type": "essay", "q": "(Short Answer) Why binary tree is important?", "a": "Efficient hierarchical storage." },
{ "id": 249, "type": "essay", "q": "(Short Answer) Why sorted data is needed?", "a": "To perform binary search." },
{ "id": 250, "type": "essay", "q": "(Short Answer) Why nodes are important?", "a": "They store data in structures." }
];