const allQuestionsData = [

  { "id": 1, "type": "tf", "q": "(True or False) Digital art is based on data rather than physical materials", "a": "True" },
  { "id": 2, "type": "tf", "q": "(True or False) Digital art is only about decoration.", "a": "False" },
  { "id": 3, "type": "tf", "q": "(True or False) Software can think and create ideas independently.", "a": "False" },
  { "id": 4, "type": "tf", "q": "(True or False) Intent helps define the purpose of a design.", "a": "True" },
  { "id": 5, "type": "tf", "q": "(True or False) Random decisions improve communication.", "a": "False" },
  { "id": 6, "type": "mcq", "q": "Digital art depends on:", "opts": ["Physical materials", "Data", "Ink", "Paint"], "a": "Data" },
  { "id": 7, "type": "mcq", "q": "The main goal of design is:", "opts": ["Decoration", "Communication", "Randomness", "Effects"], "a": "Communication" },
  { "id": 8, "type": "essay", "q": "(Complete) Digital art is a system of input, __________, and output.", "a": "transformation" },
  { "id": 9, "type": "essay", "q": "(Complete) Creativity exists in your __________, not in the tool.", "a": "decisions" },
  { "id": 10, "type": "essay", "q": "(Complete) A good design must communicate a clear __________.", "a": "message" },
  { "id": 11, "type": "essay", "q": "(Complete) The process of improving design is called __________.", "a": "iteration" },
  { "id": 12, "type": "essay", "q": "(Complete) Before designing, you must define your __________.", "a": "intent" },
  { "id": 13, "type": "essay", "q": "(Comparison) digital art & traditional art", "a": "Digital art allows undo and editing while traditional art is hard to correct." },
  { "id": 14, "type": "essay", "q": "(Comparison) random design & intentional design", "a": "Random design has weak communication while intentional design has strong communication." },
  { "id": 15, "type": "essay", "q": "(Comparison) tools & decisions", "a": "Tools execute actions while decisions create meaning." },
  { "id": 16, "type": "essay", "q": "(Comparison) clear design & cluttered design", "a": "Clear design is easy to read while cluttered design is difficult to read." },
  { "id": 17, "type": "essay", "q": "(Comparison) decoration-based design & communication-based design", "a": "Decoration-based design focuses on appearance while communication-based design focuses on message." },
  { "id": 18, "type": "essay", "q": "(Comparison) transformation & output", "a": "Transformation is the process while output is the final result." },
  { "id": 19, "type": "essay", "q": "(Mention) the components of a good design", "a": "Visual choices, Technical tools, Human understanding" },
  { "id": 20, "type": "essay", "q": "(Mention) the parts of the digital art system", "a": "Input, Transformation, Output" },
  { "id": 21, "type": "essay", "q": "(Mention) three actions possible in digital art", "a": "Move, Resize, Delete" },
  { "id": 22, "type": "essay", "q": "(Definition) Intent", "a": "Intent is the purpose, audience, and message of a design." },
  { "id": 23, "type": "essay", "q": "(Definition) Iteration", "a": "Iteration is the process of improving a design through multiple versions." },
  { "id": 24, "type": "essay", "q": "(Definition) Transformation", "a": "Transformation is the process of converting an idea into a visual form." },
  { "id": 25, "type": "essay", "q": "(Definition) Input", "a": "Input is the original idea of the design." },
  { "id": 26, "type": "essay", "q": "(Definition) Output", "a": "Output is the final visual result." },
  { "id": 27, "type": "essay", "q": "(Definition) Visual Communication", "a": "Visual communication is delivering a message through visuals." },
  { "id": 28, "type": "essay", "q": "(Definition) Design System", "a": "A design system is a structured process of input, transformation, and output." },
  { "id": 29, "type": "essay", "q": "(Definition) Reversibility", "a": "Reversibility is the ability to undo and modify actions." },
  { "id": 30, "type": "essay", "q": "(Definition) Random Design", "a": "Random design is creating visuals without intent." },
  { "id": 31, "type": "essay", "q": "(Definition) Intentional Design", "a": "Intentional design is creating visuals based on purpose." },
  { "id": 32, "type": "essay", "q": "(Definition) Clarity", "a": "Clarity is how easily the message is understood." },
  { "id": 33, "type": "essay", "q": "(Definition) Visual Noise", "a": "Visual noise is unnecessary elements that reduce clarity." },
  { "id": 34, "type": "essay", "q": "(Definition) Structured Design", "a": "Structured design is organized and clear." },
  { "id": 35, "type": "essay", "q": "(Definition) Unstructured Design", "a": "Unstructured design is a design created without planning, clear goals, or a defined process." },
  { "id": 36, "type": "essay", "q": "(Explain) why digital art is considered a system", "a": "Because it consists of input, transformation, and output working together." },
  { "id": 37, "type": "essay", "q": "(Explain) why decisions are more important than tools", "a": "Because tools only execute while decisions create meaning." },
  { "id": 38, "type": "essay", "q": "(Explain) why intent must be defined before designing", "a": "Because it guides all design choices." },
  { "id": 39, "type": "essay", "q": "(Explain) how iteration improves design quality", "a": "Because it allows continuous improvement." },
  { "id": 40, "type": "essay", "q": "(Explain) why digital art allows experimentation", "a": "Because actions can be undone easily." },
  { "id": 41, "type": "essay", "q": "(Explain) the role of transformation in design", "a": "Because it converts the idea into a visual form." },
  { "id": 42, "type": "essay", "q": "(Explain) why a design may fail even if it looks good", "a": "Because it may not communicate the message." },
  { "id": 43, "type": "essay", "q": "(Explain) how clarity affects communication", "a": "Because clear design improves understanding." },
  { "id": 44, "type": "essay", "q": "(Explain) why designers should think before using tools", "a": "Because planning leads to better results." },
  { "id": 45, "type": "essay", "q": "(List) the three main questions designers must answer before designing", "a": "What is the message, Who is the audience, How to make the message clear" },
  { "id": 46, "type": "essay", "q": "(List) the stages of the digital art system", "a": "Input, Transformation, Output, Iteration, Communication" },
  { "id": 47, "type": "essay", "q": "(List) four characteristics of digital art", "a": "Editable, Flexible, Data-based, Reversible" },
  { "id": 48, "type": "essay", "q": "(List) four design elements that affect communication", "a": "Color, Typography, Layout, Contrast" },
  { "id": 49, "type": "essay", "q": "(List) four advantages of digital art", "a": "Easy editing, Undo feature, Fast changes, Multiple versions" },
  { "id": 50, "type": "essay", "q": "(List) four problems caused by random design", "a": "Confusion, Weak message, Visual noise, Poor structure" },



  
  { "id": 51, "type": "tf", "q": "(True or False) A structured workflow improves design quality", "a": "True" },
  { "id": 52, "type": "tf", "q": "(True or False) Skipping planning leads to better results", "a": "False" },
  { "id": 53, "type": "tf", "q": "(True or False) Version 1 is the final design", "a": "False" },
  { "id": 54, "type": "tf", "q": "(True or False) A workflow helps reduce confusion", "a": "True" },
  { "id": 55, "type": "tf", "q": "(True or False) Professional designers follow a clear process", "a": "True" },
  { "id": 56, "type": "tf", "q": "(True or False) Feedback is only personal opinion", "a": "False" },
  { "id": 57, "type": "tf", "q": "(True or False) Review comes before revision", "a": "True" },
  { "id": 58, "type": "tf", "q": "(True or False) Organization is part of professional work", "a": "True" },
  { "id": 59, "type": "tf", "q": "(True or False) The workflow stages must always be followed in order without returning back", "a": "False" },
  { "id": 60, "type": "tf", "q": "(True or False) A design brief is optional", "a": "False" },
  { "id": 61, "type": "tf", "q": "(True or False) Constraints help guide design decisions", "a": "True" },
  { "id": 62, "type": "mcq", "q": "The first stage of workflow is:", "opts": ["Intent", "Plan", "Review", "Export"], "a": "Intent" },
  { "id": 63, "type": "mcq", "q": "The purpose of a design brief is to define:", "opts": ["Effects", "Audience and message", "Colors only", "Export"], "a": "Audience and message" },
  { "id": 64, "type": "mcq", "q": "Version 1 is:", "opts": ["First draft", "Second draft", "Exported file", "Finished work"], "a": "First draft" },
  { "id": 65, "type": "mcq", "q": "Feedback should be treated as:", "opts": ["Opinion", "Decoration", "Technical input", "Final judgment"], "a": "Technical input" },
  { "id": 66, "type": "mcq", "q": "A structured workflow reduces:", "opts": ["Creativity", "Confusion", "Quality", "Clarity"], "a": "Confusion" },
  { "id": 67, "type": "essay", "q": "(Complete) A workflow is a clear order of _________.", "a": "steps" },
  { "id": 68, "type": "essay", "q": "(Complete) The first stage of workflow is _________.", "a": "intent" },
  { "id": 69, "type": "essay", "q": "(Complete) Version 1 is the _________ version of the design.", "a": "first" },
  { "id": 70, "type": "essay", "q": "(Complete) Feedback is considered _________ input.", "a": "technical" },
  { "id": 71, "type": "essay", "q": "(Complete) Revision focuses on _________ improvement.", "a": "controlled" },
  { "id": 72, "type": "essay", "q": "(Complete) A design brief defines the _________ and audience.", "a": "message" },
  { "id": 73, "type": "essay", "q": "(Complete) Constraints help reduce _________ decisions.", "a": "random" },
  { "id": 74, "type": "essay", "q": "(Complete) The final stage is called _________.", "a": "final output" },
  { "id": 75, "type": "essay", "q": "(Complete) Review helps identify _________.", "a": "weaknesses" },
  { "id": 76, "type": "essay", "q": "(Complete) Professional designers avoid _________ changes.", "a": "random" },
  { "id": 77, "type": "essay", "q": "(Comparison) structured design & unstructured design", "a": "Structured design is organized while unstructured design is random." },
  { "id": 78, "type": "essay", "q": "(Comparison) structured workflow & random workflow", "a": "Structured workflow follows clear steps while random workflow has no order." },
  { "id": 79, "type": "essay", "q": "(Comparison) Version 1 & final output", "a": "Version 1 is the first draft while final output is the refined result." },
  { "id": 80, "type": "essay", "q": "(Comparison) review & revise", "a": "Review identifies problems while revise improves them." },
  { "id": 81, "type": "essay", "q": "(Comparison) brief-based design & no-brief design", "a": "Brief-based design is clear and focused while no-brief design is random." },
  { "id": 82, "type": "essay", "q": "(Comparison) feedback & opinion", "a": "Feedback is logical and structured while opinion is personal." },
  { "id": 83, "type": "essay", "q": "(Comparison) planning & random start", "a": "Planning organizes ideas while random start causes confusion." },
  { "id": 84, "type": "essay", "q": "(Mention) the six stages of workflow", "a": "Intent, Plan, Create, Review, Revise, Final Output" },
  { "id": 85, "type": "essay", "q": "(Mention) the five parts of a design brief", "a": "Project goal, Target audience, Main message, Platform, Constraints" },
  { "id": 86, "type": "essay", "q": "(Mention) three benefits of structured workflow", "a": "Reduce confusion, Save time, Improve quality" },
  { "id": 87, "type": "essay", "q": "(Mention) three problems caused by skipping planning", "a": "Confusion, Weak structure, Poor communication" },
  { "id": 88, "type": "essay", "q": "(Mention) three elements checked in feedback", "a": "Clarity, Hierarchy, Alignment" },
  { "id": 89, "type": "essay", "q": "(Definition) structured workflow", "a": "A structured workflow is a sequence of steps used to complete a design professionally." },
  { "id": 90, "type": "essay", "q": "(Definition) design brief", "a": "A design brief is a short document that defines the goal, audience, and message." },
  { "id": 91, "type": "essay", "q": "(Definition) feedback", "a": "Feedback is structured evaluation used to improve design." },
  { "id": 92, "type": "essay", "q": "(Definition) revision", "a": "Revision is controlled improvement of specific elements." },
  { "id": 93, "type": "essay", "q": "(Definition) refinement", "a": "Refinement is improving small details for precision." },
  { "id": 94, "type": "essay", "q": "(Explain) why structured workflow improves design quality", "a": "Because it organizes steps and improves clarity and quality." },
  { "id": 95, "type": "essay", "q": "(Explain) why Version 1 is not final", "a": "Because it is only the first attempt and may contain mistakes." },
  { "id": 96, "type": "essay", "q": "(Explain) why feedback is important in design", "a": "Because it identifies weaknesses and improves clarity." },
  { "id": 97, "type": "essay", "q": "(Explain) how constraints improve creativity", "a": "Because constraints guide decisions and reduce randomness." },
  { "id": 98, "type": "essay", "q": "(Explain) why planning is important before designing", "a": "Because it defines structure and prevents confusion." },
  { "id": 99, "type": "essay", "q": "(Explain) why workflow is iterative not linear", "a": "Because designers may return to improve earlier stages." },
  { "id": 100, "type": "essay", "q": "(Explain) how organization helps designers", "a": "Because it keeps files organized and easy to manage." }



  ,
  { "id": 101, "type": "tf", "q": "(True or False) Visual hierarchy controls what the viewer sees first", "a": "True" },
  { "id": 102, "type": "tf", "q": "(True or False) If all elements are equal, the design has strong hierarchy", "a": "False" },
  { "id": 103, "type": "tf", "q": "(True or False) Balance affects how stable a design feels", "a": "True" },
  { "id": 104, "type": "tf", "q": "(True or False) Visual weight depends only on size", "a": "False" },
  { "id": 105, "type": "tf", "q": "(True or False) Low contrast improves readability", "a": "False" },
  { "id": 106, "type": "tf", "q": "(True or False) Alignment has no effect on design clarity", "a": "False" },
  { "id": 107, "type": "tf", "q": "(True or False) Spacing helps reduce visual noise", "a": "True" },
  { "id": 108, "type": "essay", "q": "(Complete) Hierarchy controls viewer __________.", "a": "attention" },
  { "id": 109, "type": "essay", "q": "(Complete) Balance creates visual __________.", "a": "stability" },
  { "id": 110, "type": "essay", "q": "(Complete) Contrast improves __________.", "a": "readability" },
  { "id": 111, "type": "essay", "q": "(Complete) Spacing reduces visual __________.", "a": "noise" },
  { "id": 112, "type": "essay", "q": "(Complete) Alignment creates _________.", "a": "clarity" },
  { "id": 113, "type": "essay", "q": "(Complete) Visual weight depends on color and __________.", "a": "size" },
  { "id": 114, "type": "essay", "q": "(Complete) Good composition improves __________.", "a": "attention" },
  { "id": 115, "type": "essay", "q": "(Comparison) hierarchy & no hierarchy", "a": "Hierarchy guides the viewer’s attention; no hierarchy creates confusion." },
  { "id": 116, "type": "essay", "q": "(Comparison) symmetrical balance & asymmetrical balance", "a": "Symmetrical balance feels stable; asymmetrical balance feels dynamic." },
  { "id": 117, "type": "essay", "q": "(Comparison) high contrast & low contrast", "a": "High contrast improves readability; low contrast reduces readability." },
  { "id": 118, "type": "essay", "q": "(Comparison) aligned design & misaligned design", "a": "Aligned design creates clarity; misaligned design creates disorder." },
  { "id": 119, "type": "essay", "q": "(Comparison) spaced layout & crowded layout", "a": "Spaced layout reduces visual noise; crowded layout feels cluttered." },
  { "id": 120, "type": "essay", "q": "(Mention) four tools that control hierarchy", "a": "Size, Color, Position / Layout, Typography" },
  { "id": 121, "type": "essay", "q": "(Mention) four factors affecting visual weight", "a": "Size, Color, Shape, Texture or density" },
  { "id": 122, "type": "essay", "q": "(Mention) four types of contrast", "a": "Color contrast, Size contrast, Shape contrast, Texture contrast" },
  { "id": 123, "type": "essay", "q": "(Mention) four problems caused by low contrast", "a": "Poor readability, Eye strain, Important elements overlooked, Confusion or lack of focus" },
  { "id": 124, "type": "essay", "q": "(Mention) four benefits of spacing", "a": "Reduces visual noise, Improves readability, Organizes elements clearly, Guides viewer attention" },
  { "id": 125, "type": "essay", "q": "(Definition) visual hierarchy", "a": "The arrangement of elements in a design that guides the viewer’s attention and shows what is most important first." },
  { "id": 126, "type": "essay", "q": "(Definition) balance", "a": "The distribution of visual elements in a design to create a sense of stability and harmony." },
  { "id": 127, "type": "essay", "q": "(Definition) visual weight", "a": "How much an element attracts the viewer’s attention based on its size, color, shape, and texture." },
  { "id": 128, "type": "essay", "q": "(Definition) contrast", "a": "The difference between elements, such as color, size, or shape." },
  { "id": 129, "type": "essay", "q": "(Definition) spacing", "a": "The empty space between elements in a design that reduces clutter and improves clarity." },
  { "id": 130, "type": "tf", "q": "(True or False) A large red circle has more visual weight than a small grey circle.", "a": "True" },
  { "id": 131, "type": "tf", "q": "(True or False) White space is a waste of design space.", "a": "False" },
  { "id": 132, "type": "tf", "q": "(True or False) Contrast can be created using different fonts.", "a": "True" },
  { "id": 133, "type": "mcq", "q": "Which type of balance is formal and mirrored?", "opts": ["Asymmetrical", "Symmetrical", "Radial", "Discordant"], "a": "Symmetrical" },
  { "id": 134, "type": "mcq", "q": "Negative space is another name for:", "opts": ["Spacing", "Visual noise", "Error", "Dark colors"], "a": "Spacing" },
  { "id": 135, "type": "mcq", "q": "To make a title stand out, you should use:", "opts": ["Lower contrast", "Smaller size", "Visual hierarchy", "No alignment"], "a": "Visual hierarchy" },
  { "id": 136, "type": "mcq", "q": "Visual weight is affected by:", "opts": ["Size and color", "Software price", "Internet speed", "File name"], "a": "Size and color" },
  { "id": 137, "type": "mcq", "q": "Alignment helps a design look:", "opts": ["Random", "Professional and organized", "Cluttered", "Invisible"], "a": "Professional and organized" },
  { "id": 138, "type": "essay", "q": "(Complete) Symmetrical balance feels __________ and formal.", "a": "stable" },
  { "id": 139, "type": "essay", "q": "(Complete) Using a bold font next to a thin font is an example of __________ contrast.", "a": "typography/size" },
  { "id": 140, "type": "essay", "q": "(Complete) Elements that are close together are perceived as a __________.", "a": "group" },
  { "id": 141, "type": "essay", "q": "(Mention) Three ways to create visual hierarchy", "a": "Increasing size, using bold colors, placing elements at the top." },
  { "id": 142, "type": "essay", "q": "(Mention) Two types of balance", "a": "Symmetrical and Asymmetrical balance." },
  { "id": 143, "type": "essay", "q": "(Explain) Why center alignment is often used for invitations", "a": "Because it creates a sense of formality and balance." },
  { "id": 144, "type": "essay", "q": "(Explain) How color contrast improves accessibility", "a": "By making text easier to read for people with visual impairments." },
  { "id": 145, "type": "essay", "q": "(Explain) The effect of too much visual noise", "a": "It makes the design confusing and hard to understand." },
  { "id": 146, "type": "essay", "q": "(Comparison) Large elements & Small elements", "a": "Large elements have more visual weight; small elements have less." },
  { "id": 147, "type": "essay", "q": "(Comparison) Bright colors & Muted colors", "a": "Bright colors attract more attention; muted colors stay in the background." },
  { "id": 148, "type": "essay", "q": "(List) Three tools to achieve contrast", "a": "Color, Size, Shape." },
  { "id": 149, "type": "essay", "q": "(List) Two benefits of alignment", "a": "Creates order, improves readability." },
  { "id": 150, "type": "essay", "q": "(Definition) Composition", "a": "The overall arrangement and organization of visual elements in a design." }



  ,
  { "id": 151, "type": "tf", "q": "(True or False) RGB is a color model based on Red, Green, and Blue.", "a": "True" },
  { "id": 152, "type": "tf", "q": "(True or False) HEX code represents color using 6 characters.", "a": "True" },
  { "id": 153, "type": "tf", "q": "(True or False) RGB values range from 0 to 100.", "a": "False" },
  { "id": 154, "type": "tf", "q": "(True or False) HEX colors are only used in printing.", "a": "False" },
  { "id": 155, "type": "tf", "q": "(True or False) Color in digital design is controlled by numerical values.", "a": "True" },
  { "id": 156, "type": "tf", "q": "(True or False) Designers choose colors randomly without data.", "a": "False" },
  { "id": 157, "type": "tf", "q": "(True or False) Typography only decorates text.", "a": "False" },
  { "id": 158, "type": "tf", "q": "(True or False) Typography helps organize content.", "a": "True" },
  { "id": 159, "type": "tf", "q": "(True or False) All text should have the same size.", "a": "False" },
  { "id": 160, "type": "mcq", "q": "RGB stands for:", "opts": ["Red Green Black", "Red Green Blue", "Random Gradient Base", "Real Graphic Balance"], "a": "Red Green Blue" },
  { "id": 161, "type": "mcq", "q": "Which of the following is a HEX color?", "opts": ["(255, 0, 0)", "#FF0000", "RGB(0,0,0)", "Blue"], "a": "#FF0000" },
  { "id": 162, "type": "mcq", "q": "Color in digital systems is:", "opts": ["Emotional only", "Random", "Data based", "Printed only"], "a": "Data based" },
  { "id": 163, "type": "mcq", "q": "Typography is used to:", "opts": ["Add random decoration", "Structure and organize content", "Only change colors", "Remove text"], "a": "Structure and organize content" },
  { "id": 164, "type": "essay", "q": "(Complete) RGB values range from ___ to ___.", "a": "0 to 255" },
  { "id": 165, "type": "essay", "q": "(Complete) HEX color starts with ___.", "a": "#" },
  { "id": 166, "type": "essay", "q": "(Complete) Color is made of _________.", "a": "numbers / data" },
  { "id": 167, "type": "essay", "q": "(Complete) Designers control color using __________ values.", "a": "numeric" },
  { "id": 168, "type": "essay", "q": "(Explain) Why is typography considered structure, not decoration?", "a": "Because it organizes content and guides the reader." },
  { "id": 169, "type": "tf", "q": "(True or False) Black in RGB is represented by (0, 0, 0).", "a": "True" },
  { "id": 170, "type": "tf", "q": "(True or False) White in RGB is represented by (255, 255, 255).", "a": "True" },
  { "id": 171, "type": "tf", "q": "(True or False) Sans-serif fonts have small decorative lines at the ends of characters.", "a": "False" },
  { "id": 172, "type": "mcq", "q": "How many color combinations can be created with RGB?", "opts": ["100", "1,000", "Over 16 million", "Exactly 256"], "a": "Over 16 million" },
  { "id": 173, "type": "mcq", "q": "Which color model is used specifically for digital screens?", "opts": ["CMYK", "RGB", "RYB", "Pantone"], "a": "RGB" },
  { "id": 174, "type": "mcq", "q": "The space between lines of text is called:", "opts": ["Kerning", "Leading", "Tracking", "Alignment"], "a": "Leading" },
  { "id": 175, "type": "mcq", "q": "The primary goal of digital typography is:", "opts": ["Color", "Readability", "Decoration", "File size"], "a": "Readability" },
  { "id": 176, "type": "essay", "q": "(Complete) HEX stands for __________ color code.", "a": "Hexadecimal" },
  { "id": 177, "type": "essay", "q": "(Complete) Fonts with decorative strokes are called __________ fonts.", "a": "Serif" },
  { "id": 178, "type": "essay", "q": "(Complete) Using different font weights creates visual __________.", "a": "hierarchy" },
  { "id": 179, "type": "essay", "q": "(Complete) RGB is an __________ color model where light is added together.", "a": "additive" },
  { "id": 180, "type": "essay", "q": "(Mention) Three primary colors in the RGB model.", "a": "Red, Green, Blue." },
  { "id": 181, "type": "essay", "q": "(Mention) Three ways typography improves design.", "a": "Organizes information, sets the mood, improves readability." },
  { "id": 182, "type": "essay", "q": "(Explain) Why do designers use HEX codes instead of just color names?", "a": "To ensure exact color precision across different software and screens." },
  { "id": 183, "type": "essay", "q": "(Explain) The importance of contrast in typography.", "a": "It makes the text stand out from the background and easier to read." },
  { "id": 184, "type": "essay", "q": "(Explain) How color affects the message of a design.", "a": "Different colors evoke different emotions and help guide user attention." },
  { "id": 185, "type": "essay", "q": "(Comparison) Serif vs. Sans-Serif fonts.", "a": "Serif fonts have decorative feet; Sans-Serif fonts are clean and have no feet." },
  { "id": 186, "type": "essay", "q": "(Comparison) RGB vs. CMYK.", "a": "RGB is for digital screens (light); CMYK is for physical printing (ink)." },
  { "id": 187, "type": "essay", "q": "(List) Two common font styles.", "a": "Bold, Italic." },
  { "id": 188, "type": "essay", "q": "(List) Three elements of typography.", "a": "Font size, Line spacing, Font style." },
  { "id": 189, "type": "essay", "q": "(Definition) RGB Model.", "a": "A system for representing colors on a screen using combinations of Red, Green, and Blue light." },
  { "id": 190, "type": "essay", "q": "(Definition) HEX Code.", "a": "A 6-digit code used in HTML and CSS to define specific colors." },
  { "id": 191, "type": "essay", "q": "(Definition) Kerning.", "a": "The adjustment of space between individual characters in a font." },
  { "id": 192, "type": "tf", "q": "(True or False) Higher RGB values result in brighter colors.", "a": "True" },
  { "id": 193, "type": "tf", "q": "(True or False) Typography hierarchy helps the reader know where to start.", "a": "True" },
  { "id": 194, "type": "mcq", "q": "A HEX code like #000000 represents which color?", "opts": ["White", "Red", "Blue", "Black"], "a": "Black" },
  { "id": 195, "type": "mcq", "q": "Which font type is usually considered more modern?", "opts": ["Serif", "Script", "Sans-Serif", "Old Style"], "a": "Sans-Serif" },
  { "id": 196, "type": "essay", "q": "(Complete) Changing the __________ of text can make a title look more important.", "a": "size/weight" },
  { "id": 197, "type": "essay", "q": "(Complete) Digital screens create color by mixing __________.", "a": "light" },
  { "id": 198, "type": "essay", "q": "(mention) Two examples of where HEX codes are used.", "a": "Web design, UI design software." },
  { "id": 199, "type": "essay", "q": "(Explain) Why small font sizes should be avoided for body text.", "a": "Because they cause eye strain and make the content hard to read." },
  { "id": 200, "type": "essay", "q": "(Definition) Legibility.", "a": "How easy it is to distinguish one character from another in a particular typeface." }
,


  { "id": 201, "type": "tf", "q": "(True or False) UX focuses on user experience.", "a": "True" },
  { "id": 202, "type": "tf", "q": "(True or False) UI is only about code.", "a": "False" },
  { "id": 203, "type": "tf", "q": "(True or False) Animation adds movement to visuals.", "a": "True" },
  { "id": 204, "type": "tf", "q": "(True or False) Workflow helps organize design steps.", "a": "True" },
  { "id": 205, "type": "tf", "q": "(True or False) Designers can ignore users.", "a": "False" },
  { "id": 206, "type": "tf", "q": "(True or False) Feedback improves design quality.", "a": "True" },
  { "id": 207, "type": "tf", "q": "(True or False) UI and UX are identical.", "a": "False" },
  { "id": 208, "type": "tf", "q": "(True or False) Testing is part of workflow.", "a": "True" },
  { "id": 209, "type": "tf", "q": "(True or False) Good UX makes products easy to use.", "a": "True" },
  { "id": 210, "type": "tf", "q": "(True or False) Animation is only used in movies.", "a": "False" },
  { "id": 211, "type": "mcq", "q": "UX means:", "opts": ["User Experience", "User Export", "User Example", "User Effect"], "a": "User Experience" },
  { "id": 212, "type": "mcq", "q": "UI focuses on:", "opts": ["Code", "Visual interface", "Sound", "Testing"], "a": "Visual interface" },
  { "id": 213, "type": "mcq", "q": "Animation is:", "opts": ["Static", "Moving visuals", "Text", "Code"], "a": "Moving visuals" },
  { "id": 214, "type": "mcq", "q": "Workflow helps to:", "opts": ["Confuse", "Organize", "Delete", "Ignore"], "a": "Organize" },
  { "id": 215, "type": "mcq", "q": "Good UX should be:", "opts": ["Complex", "Easy to use", "Random", "Difficult"], "a": "Easy to use" },
  { "id": 216, "type": "essay", "q": "(Complete) UI stands for user __________.", "a": "interface" },
  { "id": 217, "type": "essay", "q": "(Complete) UX focuses on user __________.", "a": "experience" },
  { "id": 218, "type": "essay", "q": "(Complete) Workflow is a sequence of __________.", "a": "steps" },
  { "id": 219, "type": "essay", "q": "(Complete) Animation adds __________ to design.", "a": "movement" },
  { "id": 220, "type": "essay", "q": "(Complete) Feedback improves _________.", "a": "quality" },
  { "id": 221, "type": "essay", "q": "(Explain) what UX means.", "a": "UX means how users feel when using a product." },
  { "id": 222, "type": "essay", "q": "(Explain) what UI means.", "a": "UI means the visual design and layout users interact with visually." },
  { "id": 223, "type": "essay", "q": "(Explain) the difference between UI and UX.", "a": "UI is the look, UX is the experience." },
  { "id": 224, "type": "essay", "q": "(Explain) why UX is important in design.", "a": "UX is important because it makes products easy and enjoyable." },
  { "id": 225, "type": "essay", "q": "(Explain) the role of UI in application.", "a": "UI helps users interact with the system visually." },
  { "id": 226, "type": "essay", "q": "(Explain) how workflow improves design quality.", "a": "Workflow organizes steps and improves efficiency." },
  { "id": 227, "type": "essay", "q": "(Explain) why planning is important before designing.", "a": "Planning avoids mistakes and saves time." },
  { "id": 228, "type": "essay", "q": "(Explain) the importance of feedback.", "a": "Feedback helps improve and fix problems." },
  { "id": 229, "type": "essay", "q": "(Explain) the role of testing in UX.", "a": "Testing ensures the design works correctly and meets user needs." },
  { "id": 230, "type": "essay", "q": "(Explain) how animation improves user experience.", "a": "Animation makes design more engaging and clearer." },
  { "id": 231, "type": "essay", "q": "(Explain) why designers must understand users.", "a": "Designers must understand users to meet their needs." },
  { "id": 232, "type": "essay", "q": "(Explain) how UI affects UX.", "a": "UI affects UX by making interaction easy or difficult." },
  { "id": 233, "type": "essay", "q": "(Explain) why workflow is not random.", "a": "Workflow is structured to ensure good results." },
  { "id": 234, "type": "essay", "q": "(Explain) how iteration improves design.", "a": "Iteration improves design through repeated enhancement." },
  { "id": 235, "type": "essay", "q": "(Explain) why revision is important.", "a": "Revision fixes errors and improves quality." },
  { "id": 236, "type": "essay", "q": "(Explain) how animation can guide attention.", "a": "Animation guides user attention to important elements." },
  { "id": 237, "type": "essay", "q": "(Explain) why simple design improves UX.", "a": "Simple design makes usage easier." },
  { "id": 238, "type": "essay", "q": "(Explain) how interaction improves user experience.", "a": "Interaction makes the experience engaging." },
  { "id": 239, "type": "essay", "q": "(Explain) why consistency is important in UI.", "a": "Consistency makes design predictable and easy." },
  { "id": 240, "type": "essay", "q": "(Explain) how poor UX affects users.", "a": "Poor UX causes confusion and frustration." },
  { "id": 241, "type": "essay", "q": "(Comparison) UI vs UX", "a": "UI: Visual design, colors, buttons, appearance. UX: User experience, usability, ease of use." },
  { "id": 242, "type": "essay", "q": "(Comparison) Good UX vs bad UX", "a": "Good UX: Easy, fast, clear. Bad UX: Confusing, slow, frustrating." },
  { "id": 243, "type": "essay", "q": "(Comparison) Animation vs static design", "a": "Animation: Movement, dynamic, engaging. Static: No movement, fixed content." },
  { "id": 244, "type": "essay", "q": "(Comparison) Structured workflow vs random workflow", "a": "Structured: Organized steps, efficient. Random: No order, confusing process." },
  { "id": 245, "type": "essay", "q": "(Mention) the stages of creative workflow.", "a": "Planning - Design - Testing" },
  { "id": 246, "type": "essay", "q": "(Mention) three goals of UX design.", "a": "Easy, Useful, Enjoyable" },
  { "id": 247, "type": "essay", "q": "(Mention) three UI elements.", "a": "Buttons, Icons, Colors" },
  { "id": 248, "type": "essay", "q": "(Mention) three benefits of animation.", "a": "Engagement, Clarity, Guidance" },
  { "id": 249, "type": "essay", "q": "(Mention) three features of good UX.", "a": "Simple, Clear, Fast" },
  { "id": 250, "type": "essay", "q": "(Definition) Prototyping.", "a": "The process of creating a preliminary model of a product to test a concept or process." }

];